// 📁 src/config/categories/animals.js
export const animalsConfig = {
  title: "Animal Kingdom",
  level1: [
    { id: "pets", label: "Pets" },
    { id: "aquariumFish", label: "Aquarium Fish" },
    { id: "accessories", label: "Accessories" },
    { id: "careProducts", label: "Care Products" },
    { id: "feedFood", label: "Feed & Food" },
    { id: "poultry", label: "Poultry" },
    { id: "cattle", label: "Cattle" },
    { id: "smallAnimals", label: "Small Animals" },
    { id: "seaCreatures", label: "Sea Creatures" },
    { id: "reptiles", label: "Reptiles" },
    { id: "insects", label: "Insects" },
  ],
  level2: {
    pets: [
      { id: "cat", label: "Cat" },
      { id: "dog", label: "Dog" },
      { id: "guineaPig", label: "Guinea Pig" },
      { id: "hamster", label: "Hamster" },
      { id: "tortoise", label: "Tortoise" },
      { id: "bird", label: "Bird" },
      { id: "monkey", label: "Monkey" },
      { id: "rabbit", label: "Rabbit" },
    ],
    aquariumFish: [
      { id: "invertebrates", label: "Invertebrates" },
      { id: "africanTetras", label: "African Tetras" },
      { id: "americanTetras", label: "American Tetras" },
      { id: "arowanas", label: "Arowanas" },
      { id: "livebearers", label: "Livebearers" },
      { id: "cichlids", label: "Cichlids" },
      { id: "goldfish", label: "Goldfish" },
      { id: "labyrinthFish", label: "Labyrinth Fish" },
      { id: "cyprinidae", label: "Cyprinidae" },
      { id: "stingrayCatfish", label: "Stingray & Catfish" },
      { id: "eelsMorayEels", label: "Eels / Moray Eels" },
      { id: "bulkSales", label: "Bulk Sales" },
    ],
    accessories: [
      { id: "dog", label: "Dog" },
      { id: "cat", label: "Cat" },
      { id: "bird", label: "Bird" },
      { id: "fish", label: "Fish" },
      { id: "rodent", label: "Rodent" },
      { id: "reptile", label: "Reptile" },
      { id: "cattle & sheep", label: "Cattle & Sheep" },
      { id: "poultry", label: "Poultry" },
      { id: "insects", label: "Insects" },
      { id: "bulk sales", label: "Bulk Sales" },
    ],
    careProducts: [
      { id: "cat", label: "Cat" },
      { id: "dog", label: "Dog" },
      { id: "fish", label: "Fish" },
      { id: "bird", label: "Bird" },
      { id: "rodent", label: "Rodent" },
      { id: "reptile", label: "Reptile" },
      { id: "poultry", label: "Poultry" },
      { id: "cattle & sheep", label: "Cattle & Sheep" },
      { id: "insects", label: "Insects" },
    ],
    feedFood: [
      { id: "cat", label: "Cat" },
      { id: "dog", label: "Dog" },
      { id: "fish", label: "Fish" },
      { id: "reptile", label: "Reptile" },
      { id: "rodent", label: "Rodent" },
      { id: "bird", label: "Bird" },
      { id: "poultry", label: "Poultry" },
      { id: "small & large cattle", label: "Small & Large Cattle" },
      { id: "bug", label: "Bug" },
    ],
    poultry: [
      { id: "ostrich", label: "Ostrich" },
      { id: "pigeon", label: "Pigeon" },
      { id: "turkey", label: "Turkey" },
      { id: "cockerel", label: "Cockerel" },
      { id: "goose", label: "Goose" },
      { id: "swan", label: "Swan" },
      { id: "duck", label: "Duck" },
      { id: "chicken", label: "Chicken" },
      { id: "peacock", label: "Peacock" },
      { id: "hatching eggs", label: "Hatching Eggs" },
    ],
    cattle: [
      { id: "horse", label: "Horse" },
      { id: "bull", label: "Bull" },
      { id: "camel", label: "Camel" },
      { id: "donkey", label: "Donkey" },
      { id: "cow", label: "Cow" },
      { id: "lama", label: "Lama" },
      { id: "mandate", label: "Mandate" },
    ],
    smallAnimals: [
      { id: "goat", label: "Goat" },
      { id: "ram", label: "Ram" },
      { id: "sheep", label: "Sheep" },
      { id: "lamb", label: "Lamb" },
      { id: "pig", label: "Pig" },
    ],
    seaCreatures: [
      { id: "marine fish", label: "Marine Fish" },
      { id: "octopus", label: "Octopus" },
      { id: "anemones", label: "Anemones" },
      { id: "sea mushroom", label: "Sea Mushroom" },
      { id: "sea sponge", label: "Sea Sponge" },
      { id: "sea rabbit", label: "Sea Rabbit" },
      { id: "starfish", label: "Starfish" },
      { id: "lobster", label: "Lobster" },
      { id: "prawn", label: "Prawn" },
      { id: "coral", label: "Coral" },
      { id: "snail", label: "Snail" },
      { id: "salamander", label: "Salamander" },
      { id: "crab", label: "Crab" },
    ],
    reptiles: [
      { id: "agama", label: "Agama" },
      { id: "iguana", label: "Iguana" },
      { id: "lizzard", label: "Lizzard" },
      { id: "frog", label: "Frog" },
      { id: "salamander", label: "Salamander" },
      { id: "skink", label: "Skink" },
      { id: "worm", label: "Worm" },
      { id: "uromastyx", label: "Uromastyx" },
      { id: "other breeds", label: "Other Breeds" },
    ],
    insects: [
      { id: "bee", label: "Bee" },
      { id: "silkworm", label: "Silkworm" },
      { id: "ant", label: "Ant" },
      { id: "other types", label: "Other Types" },
    ],
  },
  level3: {
    cat: [
      { id: "american shorthair", label: "American Shorthair" },
      { id: "ankara", label: "Ankara" },
      { id: "bengal", label: "Bengal" },
      { id: "burmese", label: "Burmese" },
      { id: "bombay", label: "Bombay" },
      { id: "british shorthair", label: "British Shorthair" },
      { id: "calico", label: "Calico" },
      { id: "colorpoint shorthair", label: "Colorpoint Shorthair" },
      { id: "chinchilla", label: "Chinchilla" },
      { id: "devon shorthair", label: "Devon Shorthair" },
      { id: "ethiopian", label: "Ethiopian" },
      { id: "himalayan", label: "Himalayan" },
      { id: "iranian", label: "Iranian" },
      { id: "maine coon", label: "Maine Coon" },
      { id: "crossbreed", label: "Crossbreed" },
      { id: "norwegian forest", label: "Norwegian Forest" },
      { id: "ragamuffin", label: "Ragamuffin" },
      { id: "ragdoll", label: "Ragdoll" },
      { id: "russian blue", label: "Russian Blue" },
      { id: "safman", label: "Safman" },
      { id: "scottish fold", label: "Scottish Fold" },
      { id: "serval", label: "Serval" },
      { id: "sphinx", label: "Sphinx" },
      { id: "siamese", label: "Siamese" },
      { id: "tuxedo", label: "Tuxedo" },
      { id: "tabby", label: "Tabby" },
      { id: "tortoiseshell", label: "Tortoiseshell" },
      { id: "van", label: "Van" },
      { id: "other races", label: "Other Races" },
    ],
    dog: [
      { id: "affenpinscher", label: "Affenpinscher" },
      { id: "afghan_hound", label: "Afghan Hound" },
      { id: "aid", label: "Aid" },
      { id: "akbash", label: "Akbash" },
      { id: "akita_inu", label: "Akita Inu" },
      { id: "alabai", label: "Alabai" },
      {
        id: "australian_shepherd_german",
        label: "Australian Shepherd (German ...)",
      },
      { id: "alpine_dachsbracke", label: "Alpine Dachsbracke" },
      { id: "american_cocker", label: "American Cocker" },
      { id: "australian_shepherd", label: "Australian Shepherd" },
      { id: "austrian_greyhound", label: "Austrian Greyhound" },
      { id: "bandog", label: "Bandog" },
      { id: "basset", label: "Basset" },
      { id: "beagle", label: "Beagle" },
      { id: "belgian_wolf", label: "Belgian Wolf" },
      { id: "bernese", label: "Bernese" },
      { id: "bichon_frise", label: "Bichon Frise" },
      { id: "blue_of_gascogne", label: "Blue of Gascogne" },
      { id: "bobtail", label: "Bobtail" },
      { id: "boerboel", label: "Boerboel" },
      { id: "border_collie", label: "Border Collie" },
      { id: "bordeaux", label: "Bordeaux" },
      { id: "borzoi", label: "Borzoi" },
      { id: "boxer", label: "Boxer" },
      { id: "brittany", label: "Brittany" },
      { id: "bulldog", label: "Bulldog" },
      { id: "bull_mastiff", label: "Bull Mastiff" },
      { id: "cane_corso", label: "Cane Corso" },
      { id: "cavalier_king_charles", label: "Cavalier King Charles" },
      { id: "chihuahua", label: "Chihuahua" },
      { id: "chinese_crested", label: "Chinese Crested" },
      { id: "chow_chow", label: "Chow Chow" },
      { id: "collie", label: "Collie" },
      { id: "coton_de_tulear", label: "Coton De Tulear" },
      { id: "forked_nose", label: "Forked Nose" },
      { id: "dachshund", label: "Dachshund" },
      { id: "dalmatian", label: "Dalmatian" },
      { id: "great_dane", label: "Great Dane" },
      { id: "doberman", label: "Doberman" },
      { id: "drahthaar", label: "Drahthaar" },
      { id: "english_bulldog", label: "English Bulldog" },
      { id: "english_cocker", label: "English Cocker" },
      { id: "english_greyhound", label: "English Greyhound" },
      { id: "english_mastiff", label: "English Mastiff" },
      { id: "english_setter", label: "English Setter" },
      { id: "entlebucher", label: "Entlebucher" },
      { id: "finnish_spitz", label: "Finnish Spitz" },
      { id: "french_bulldog", label: "French Bulldog" },
      { id: "golden_retriever", label: "Golden Retriever" },
      { id: "gordon_setter", label: "Gordon Setter" },
      { id: "grand_blue_of_gascogne", label: "Grand Blue of Gascogne" },
      { id: "husky", label: "Husky" },
      { id: "irish_setter", label: "Irish Setter" },
      { id: "irish_wolfhound", label: "Irish Wolfhound" },
      { id: "japanese_chin", label: "Japanese Chin" },
      { id: "caucasian_shepherd", label: "Caucasian Shepherd" },
      { id: "canadian_wolf", label: "Canadian Wolf" },
      { id: "colt", label: "Colt" },
      { id: "king_charles_spaniel", label: "King Charles Spaniel" },
      { id: "copy", label: "Copy" },
      { id: "corgi", label: "Corgi" },
      { id: "kurzhaar", label: "Kurzhaar" },
      { id: "labrador", label: "Labrador" },
      { id: "hungarian_vizsla", label: "Hungarian Vizsla" },
      { id: "malakii", label: "Malakii" },
      { id: "malamut", label: "Malamut" },
      { id: "mastbred", label: "Mastbred" },
      { id: "neapolitan_mastiff", label: "Neapolitan Mastiff" },
      { id: "newfoundland", label: "Newfoundland" },
      { id: "otterhound", label: "Otterhound" },
      { id: "papillon", label: "Papillon" },
      { id: "pekingese", label: "Pekingese" },
      { id: "pinscher", label: "Pinscher" },
      { id: "pointer", label: "Pointer" },
      { id: "pomeranian", label: "Pomeranian" },
      { id: "poodle", label: "Poodle" },
      { id: "presa_canario", label: "Presa Canario" },
      { id: "pug", label: "Pug" },
      { id: "rhodesian_ridgeback", label: "Rhodesian Ridgeback" },
      { id: "rottweiler", label: "Rottweiler" },
      { id: "samoyed", label: "Samoyed" },
      { id: "schnauzer", label: "Schnauzer" },
      { id: "shar_pei", label: "Shar-Pei" },
      { id: "shih_tzu", label: "Shih Tzu" },
      { id: "spanish_cocker", label: "Spanish Cocker" },
      { id: "spitz", label: "Spitz" },
      { id: "st_bernard", label: "St. Bernard" },
      { id: "terrier_airedale", label: "Terrier (Airedale)" },
      { id: "terrier_bull", label: "Terrier (Bull)" },
      { id: "terrier_fox", label: "Terrier (Fox)" },
      { id: "terrier_glen_of_imaal", label: "Terrier (Glen of Imaal)" },
      { id: "terrier_scottish", label: "Terrier (Scottish)" },
      { id: "terrier_jack_russell", label: "Terrier (Jack Russell)" },
      { id: "terrier_maltese", label: "Terrier (Maltese)" },
      { id: "terrier_manchester", label: "Terrier (Manchester)" },
      { id: "terrier_white", label: "Terrier (White)" },
      { id: "terrier_yorkshire", label: "Terrier (Yorkshire)" },
      { id: "texas_heeler", label: "Texas Heeler" },
      { id: "tibetan_spaniel", label: "Tibetan Spaniel" },
      { id: "weimaraner", label: "Weimaraner" },
      { id: "other_races", label: "Other Races" },
    ],
    guineaPig: [
      { id: "abssinian", label: "Abssinian" },
      { id: "american", label: "American" },
      { id: "buff", label: "Buff" },
      { id: "chocolate", label: "Chocolate" },
      { id: "dalmatian_black", label: "Dalmatian Black" },
      { id: "dutch_red", label: "Dutch Red" },
      { id: "golden", label: "Golden" },
      { id: "lilac", label: "Lilac" },
      { id: "peruviner", label: "Peruviner" },
      { id: "rejection", label: "Rejection" },
      { id: "rex", label: "Rex" },
      { id: "salmon_agouti", label: "Salmon Agouti" },
    ],
    hamster: [
      { id: "gonzales", label: "Gonzales" },
      { id: "robovski", label: "Robovski" },
      { id: "syrian", label: "Syrian" },
      { id: "other_races", label: "Other Races" },
    ],
    tortoise: [
      { id: "geochelone_sulcata", label: "Geochelone Sulcata" },
      { id: "black", label: "Black" },
      { id: "pelomedusa_subrufa", label: "Pelomedusa Subrufa" },
      { id: "singapore", label: "Singapore" },
      { id: "water_turtle", label: "Water Turtle" },
      { id: "terrapin", label: "Terrapin" },
      { id: "other_races", label: "Other Races" },
    ],
    bird: [
      { id: "arabian_nightingale", label: "Arabian Nightingale" },
      { id: "golden_finch", label: "Golden Finch" },
      { id: "indian_nightingale", label: "Indian Nightingale" },
      { id: "finch", label: "Finch" },
      { id: "canary", label: "Canary" },
      { id: "mayna", label: "Mayna" },
      { id: "parrot", label: "Parrot" },
      { id: "other_bird_species", label: "Other Bird Species" },
    ],
    monkey: [
      { id: "baboon", label: "Baboon" },
      { id: "witchcraft", label: "Witchcraft" },
      { id: "java", label: "Java" },
      { id: "mona", label: "Mona" },
      { id: "patas", label: "Patas" },
      { id: "rhesus", label: "Rhesus" },
      { id: "savannah", label: "Savannah" },
      { id: "chimp", label: "Chimp" },
      { id: "tamarin", label: "Tamarin" },
      { id: "macantus", label: "Macantus" },
      { id: "vervet_spider_monkey", label: "Vervet (Spider Monkey)" },
      { id: "other_races", label: "Other Races" },
    ],
    rabbit: [
      { id: "island_rabbit", label: "Island Rabbit" },
      { id: "angora", label: "Angora" },
      { id: "lionhead", label: "Lionhead" },
      { id: "chinchilla", label: "Chinchilla" },
      { id: "mountain_rabbit", label: "Mountain Rabbit" },
      { id: "english_spot", label: "English Spot" },
      { id: "flemish_giant", label: "Flemish Giant" },
      { id: "lobe", label: "Lobe" },
      { id: "new_zealand", label: "New Zealand" },
      { id: "other_races", label: "Other Races" },
    ],
    invertebrates: [
      { id: "lobster", label: "Lobster" },
      { id: "prawn", label: "Prawn" },
      { id: "crayfish", label: "Crayfish" },
      { id: "snail", label: "Snail" },
      { id: "crab", label: "Crab" },
      { id: "other_invertebrates", label: "Other Invertebrates" },
    ],
    africanTetras: [
      { id: "adonis", label: "Adonis" },
      { id: "ansorges", label: "Ansorges" },
      { id: "arnolds_red_eye", label: "Arnolds Red Eye" },
      { id: "congos", label: "Congos" },
      { id: "orange_red", label: "Orange Red" },
      { id: "yellow_congo", label: "Yellow Congo" },
      { id: "long_fins", label: "Long Fins" },
    ],
    americanTetras: [
      { id: "glassTetra", label: "Glass Tetra" },
      { id: "cardinalNeon", label: "Cardinal Neon" },
      { id: "neonFish", label: "Neon Fish" },
      { id: "neonTetra", label: "Neon Tetra" },
      { id: "pacus", label: "Pacus" },
      { id: "redNoseTetra", label: "Red Nose Tetra" },
      { id: "blackNeon", label: "Black Neon" },
      { id: "transgeneticTetra", label: "Transgenetic Tetra" },
      { id: "otherTypes", label: "Other Types" },
    ],
    arowanas: [
      { id: "africa", label: "Africa" },
      { id: "asia", label: "Asia" },
      { id: "australia", label: "Australia" },
      { id: "silver", label: "Silver" },
      { id: "black", label: "Black" },
    ],
    livebearers: [
      { id: "swordtail", label: "Swordtail" },
      { id: "guppy", label: "Guppy" },
      { id: "molly", label: "Molly" },
      { id: "platy", label: "Platy" },
      { id: "velifera", label: "Velifera" },
      { id: "otherTypes", label: "Other Types" },
    ],
    cichlids: [
      { id: "afraCobue", label: "Afra Cobue" },
      { id: "afraHara", label: "Afra Hara" },
      { id: "afraJaloReef", label: "Afra Jalo Reef" },
      { id: "people", label: "People" },
      { id: "attispinoza", label: "Attispinoza" },
      { id: "anomaly", label: "Anomaly" },
      { id: "apistogramma", label: "Apistogramma" },
      { id: "astronaut", label: "Astronaut" },
      { id: "fireMouth", label: "Fire Mouth" },
      { id: "fireHead", label: "Fire Head" },
      { id: "aulonocaraMaulana", label: "Aulonocara Maulana" },
      { id: "auratus", label: "Auratus" },
      { id: "flagFestival", label: "Flag / Festival" },
      { id: "whitePrincess", label: "White Princess" },
      { id: "borelli", label: "Borelli" },
      { id: "borley", label: "Borley" },
      { id: "brevis", label: "Brevis" },
      { id: "bricardi", label: "Bricardi" },
      { id: "calico", label: "Calico" },
      { id: "chocolateCichlid", label: "Chocolate Cichlid" },
      { id: "demasonry", label: "Demasonry" },
      { id: "discus", label: "Discus" },
      { id: "electricBlueAcara", label: "Electric Blue Acara" },
      { id: "elongatusChewere", label: "Elongatus Chewere" },
      { id: "elongatusNeonSpot", label: "Elongatus Neon Spot" },
      { id: "flowerhorn", label: "Flowerhorn" },
      { id: "frontosa", label: "Frontosa" },
      { id: "geophagus", label: "Geophagus" },
      { id: "greenTerror", label: "Green Terror" },
      { id: "hongi", label: "Hongi" },
      { id: "iceBlue", label: "Ice Blue" },
      { id: "iceman", label: "Iceman" },
      { id: "iturigi", label: "Iturigi" },
      { id: "jackDempsey", label: "Jack Dempsey" },
      { id: "jackDempseyElectricBlue", label: "Jack Dempsey Electric Blue" },
      { id: "jaguarCichlid", label: "Jaguar Cichlid" },
      { id: "johanni", label: "Johanni" },
      { id: "joker", label: "Joker" },
      { id: "cockatoo", label: "Cockatoo" },
      { id: "calvus", label: "Calvus" },
      { id: "kenyi", label: "kenyi" },
      { id: "redEmperor", label: "Red Emperor" },
      { id: "redJewel", label: "Red Jewel" },
      { id: "cobaltBlue", label: "Cobalt Blue" },
      { id: "deadhead", label: "Deadhead" },
      { id: "king", label: "King" },
      { id: "kribensis", label: "Kribensis" },
      { id: "lemonButterfly", label: "Lemon Butterfly" },
      { id: "leptosoma", label: "Leptosoma" },
      { id: "likomaPearl", label: "Likoma Pearl" },
      { id: "lemonGum", label: "Lemon Gum" },
      { id: "macawCichlid", label: "Macaw Cichlid" },
      { id: "malawi", label: "Malawi" },
      { id: "marlieri", label: "Marlieri" },
      { id: "blueEmperor", label: "Blue Emperor" },
      { id: "bluePrincess", label: "Blue Princess" },
      { id: "blueZebra", label: "Blue Zebra" },
      { id: "monkeyHead", label: "Monkey Head" },
      { id: "angelfish", label: "Angelfish" },
      { id: "midas", label: "Midas" },
      { id: "mono", label: "Mono" },
      { id: "moore", label: "Moore" },
      { id: "mpanga", label: "Mpanga" },
      { id: "msoboMagunga", label: "Msobo Magunga" },
      { id: "jewelCichlid", label: "Jewel Cichlid" },
      { id: "neolamprologus", label: "Neolamprologus" },
      { id: "ophthalmotilapia", label: "Ophthalmotilapia" },
      { id: "parrotCichlid", label: "Parrot Cichlid" },
      { id: "rustyCichlid", label: "Rusty Cichlid" },
      { id: "petrochromis", label: "Petrochromis" },
      { id: "polit", label: "Polit" },
      { id: "orangeCichlid", label: "Orange Cichlid" },
      { id: "rainbowCichlid", label: "Rainbow Cichlid" },
      { id: "ramirez", label: "Ramirez" },
      { id: "redfin", label: "Redfin" },
      { id: "redTerror", label: "Red Terror" },
      { id: "reganiCichlid", label: "Regani Cichlid" },
      { id: "yellowEmperor", label: "Yellow Emperor" },
      { id: "yellowPrincess", label: "Yellow Princess" },
      { id: "saulosiCoralRed", label: "Saulosi Coral Red" },
      { id: "saulosiCichlid", label: "Saulosi Cichlid" },
      { id: "iLoveIt", label: "I love it" },
      { id: "sweetPink", label: "Sweet Pink" },
      { id: "bandedKrebensis", label: "Banded Krebensis" },
      { id: "tanganyika", label: "Tanganyika" },
      { id: "texas", label: "Texas" },
      { id: "trewavas", label: "Trewavas Cichlid" },
      { id: "tropheus", label: "Tropheus" },
      { id: "venustus", label: "Venustus" },
      { id: "yacob", label: "Yacob" },
      { id: "livingRock", label: "Living Rock" },
      { id: "dolphin", label: "Dolphin" },
      { id: "zebra", label: "Zebra" },
      { id: "otherTypes", label: "Other Types" },
    ],
    goldfish: [
      { id: "lionhead", label: "Lionhead" },
      { id: "pearlBody", label: "Pearl Body" },
      { id: "koi", label: "Koi" },
      { id: "atTheRate", label: "At the rate" },
      { id: "ranchu", label: "Ranchu" },
      { id: "ryukin", label: "Ryukin" },
      { id: "shubunkin", label: "Shubunkin" },
      { id: "telescope", label: "Telescope" },
      { id: "tuliptail", label: "Tuliptail" },
      { id: "otherTypes", label: "Other Types" },
    ],
    labyrinthFish: [
      { id: "betta", label: "Betta" },
      { id: "paradiseFish", label: "Paradise Fish" },
      { id: "channa", label: "Channa" },
      { id: "dwarfGourami", label: "Dwarf Gourami" },
      { id: "mosaicGourami", label: "Mosaic Gourami" },
      { id: "otherTypes", label: "Other Types" },
    ],
    cyprinidae: [
      { id: "albinoFrenatus", label: "Albino Frenatus" },
      { id: "aphaniusKillifish", label: "Aphanius Killifish" },
      { id: "barbusSchwanenfeldii", label: "Barbus Schwanenfeldii" },
      { id: "botya", label: "Botya" },
      { id: "challenger", label: "Challenger" },
      { id: "chineseDragon", label: "Chinese Dragon" },
      { id: "giantDanio", label: "Giant Danio" },
      { id: "cardinal", label: "Cardinal" },
      { id: "catfish", label: "Catfish" },
      { id: "rudd", label: "Rudd" },
      { id: "shark", label: "Shark" },
      { id: "kuhliLoach", label: "Kuhli Loach" },
      { id: "rasbora", label: "Rasbora" },
      { id: "tetrazone", label: "Tetrazone" },
      { id: "crocodileFish", label: "Crocodile Fish" },
      { id: "zebraFish", label: "Zebra Fish" },
      { id: "otherTypes", label: "Other Types" },
    ],
    stingrayCatfish: [
      { id: "albinoStingray", label: "Albino Stingray" },
      { id: "botiaModesta", label: "Botia Modesta" },
      { id: "bronzeCorydoras", label: "Bronze Corydoras" },
      { id: "dwarfOtocinclus", label: "Dwarf Otocinclus" },
      { id: "dwarfRay", label: "Dwarf Ray" },
      { id: "spinyAncistrus", label: "Spiny Ancistrus" },
      { id: "commando", label: "Commando" },
      { id: "l144Longfin", label: "L144 Longfin" },
      { id: "lda16Stingray", label: "LDA16 Stingray" },
      { id: "leopardStingray", label: "Leopard Stingray" },
      { id: "clownLoach", label: "Clown Loach" },
      { id: "spottedStingray", label: "Spotted Stingray" },
      { id: "perigasos", label: "Perigasos" },
      { id: "sterbai", label: "Sterbai" },
      { id: "superRedLongfin", label: "Super Red Longfin" },
      { id: "upsideDownFloatingGarba", label: "Upside Down Floating Garba..." },
      { id: "zebraRay", label: "Zebra Ray" },
      { id: "otherTypes", label: "Other Types" },
    ],
    eelsMorayEels: [
      { id: "helenaMuren", label: "Helena Muren" },
      { id: "twoToneFalseMuren", label: "Two-Tone False Muren" },
      { id: "brownMoray", label: "Brown Moray" },
      { id: "spinyEel", label: "Spiny Eel" },
      { id: "theMigrs", label: "The Migrs" },
      { id: "purrEel", label: "Purr Eel" },
      { id: "freshwaterEel", label: "Freshwater Eel" },
    ],
  },
};