// 📁 src/config/categories/construction.js
export const constructionConfig = {
  title: "Construction Machinery & Industry",
  level1: [
    { id: "constructionMachinery", label: "Construction Machinery" },
    { id: "agriculturalMachinery", label: "Agricultural Machinery" },
    { id: "industry", label: "Industry" },
    { id: "electricityEnergy", label: "Electricity & Energy" },
  ],
  level2: {
    constructionMachinery: [
      { id: "forSale", label: "For sale" },
      { id: "forRent", label: "For rent" },
      { id: "partsAttachments", label: "Parts & Attachments" },
    ],
    agriculturalMachinery: [
      { id: "tractors", label: "Tractor" },
      { id: "soilCultivation", label: "Soil Cultivation" },
      { id: "harvestThresh", label: "Harvest & Thresh" },
      { id: "plantCare", label: "Plant Care" },
      { id: "plantingSowing", label: "Planting & Sowing" },
      { id: "fertilization", label: "Fertilization" },
      { id: "irrigation", label: "Irrigation" },
      { id: "livestockFarming", label: "Livestock farming" },
      { id: "transport", label: "Transport" },
      { id: "attachmentsSpareParts", label: "Attachments & Spare Parts" },
    ],
    industry: [
      { id: "industrialMachinery", label: "Industrial Machinery" },
      { id: "industrialKitchen", label: "Industrial Kitchen" },
      { id: "industrialFurniture", label: "Industrial Furniture" },
      { id: "industrialCleaning", label: "Industrial Cleaning" },
      { id: "industrialHardware", label: "Industrial Hardware" },
      { id: "transportStacking", label: "Transport & Stacking" },
      { id: "compressor", label: "Compressor" },
      { id: "shelvingProductDisplay", label: "Shelving & Product Display" },
      { id: "tentAwningShutter", label: "Tent, Awning & Shutter" },
      { id: "containerCabin", label: "Container & Cabin" },
      {
        id: "protectionShelterSystems",
        label: "Protection and Shelter Syste...",
      },
    ],
    electricityEnergy: [
      { id: "generator", label: "Generator" },
      { id: "electricElectronics", label: "Electric & Electronics" },
      { id: "fuelProducts", label: "Fuel Products" },
      { id: "pressureVessels", label: "Pressure Vessels" },
      { id: "solarPanel", label: "Solar panel" },
      { id: "windTurbine", label: "Wind Turbine" },
      { id: "waterTurbine", label: "Water Turbine" },
    ],
  },
  level3: {
    forSale: [
      { id: "asphaltMachine", label: "Asphalt Machine" },
      { id: "backhoeLoader", label: "Backhoe Loader (Excavator-..." },
      { id: "articulatedDumper", label: "Articulated Dumper" },
      { id: "concreteDistributor", label: "Concrete Distributor" },
      { id: "concretePump", label: "Concrete Pump" },
      { id: "garbageCompactor", label: "Garbage Compactor" },
      { id: "railwayMachine", label: "Railway Machine" },
      { id: "dieselHammer", label: "Diesel Hammer" },
      { id: "dozer", label: "Dozer" },
      { id: "excavatorBucket", label: "Excavator (Bucket)" },
      { id: "finisher", label: "Finisher" },
      { id: "boredPileMachine", label: "Bored Pile Machine" },
      { id: "grader", label: "Grader" },
      { id: "canalTrenchDigger", label: "Canal & Trench Digger" },
      { id: "snowmobile", label: "Snowmobile" },
      { id: "snowPlowTruck", label: "Snow Plow Truck" },
      { id: "snowBlower", label: "Snow Blower" },
      { id: "rockDrillAnchor", label: "Rock Drill (Anchor)" },
      { id: "rockTruck", label: "Rock Truck" },
      { id: "crushingScreeningPlant", label: "Crushing Screening Plant" },
      { id: "towerCrane", label: "Tower Crane" },
      { id: "loader", label: "Loader" },
      { id: "mobileElevator", label: "Mobile Elevator" },
      { id: "mobileCrusherRent", label: "Mobile Crusher" },
      { id: "mobileCrane", label: "Mobile Crane" },
      { id: "cylinder", label: "Cylinder" },
      { id: "drillingMachine", label: "Drilling Machine" },
      { id: "telescopicLoader", label: "Telescopic Loader" },
      { id: "transmixer", label: "Transmixer" },
    ],
    forRent: [
      { id: "asphaltMachineRent", label: "Asphalt Machine" },
      {
        id: "backhoeLoaderRent",
        label: "Backhoe Loader (Digger & L...",
      },
      { id: "concreteDistributor", label: "Concrete Distributor" },
      { id: "concretePumpRent", label: "Concrete Pump" },
      { id: "garbageCompactor", label: "Garbage Compactor" },
      { id: "dieselHammer", label: "Diesel Hammer" },
      { id: "dozerRent", label: "Dozer" },
      { id: "excavatorBucketRent", label: "Excavator (Bucket)" },
      { id: "finisherRent", label: "Finisher" },
      { id: "boredPileMachineRent", label: "Bored Pile Machine" },
      { id: "graderRent", label: "Grader" },
      { id: "canalTrenchDigger", label: "Canal & Trench Digger" },
      { id: "snowPlowTruckRent", label: "Snow Plow Truck" },
      { id: "rockDrill", label: "Rock Drill" },
      { id: "rockTruckRent", label: "Rock Truck" },
      { id: "crushingScreeningPlantRent", label: "Crushing Screening Plant" },
      { id: "towerCrane", label: "Tower Crane" },
      { id: "loaderRent", label: "Loader" },
      { id: "mobileElevator", label: "Mobile Elevator" },
      { id: "mobileCrusher", label: "Mobile Crusher" },
      { id: "mobileCrane", label: "Mobile Crane" },
      { id: "cylinder", label: "Cylinder" },
      { id: "drillingMachine", label: "Drilling Machine" },
      { id: "telescopicLoader", label: "Telescopic Loader" },
      { id: "transmixer", label: "Transmixer" },
    ],
    partsAttachments: [
      { id: "asphaltMachineParts", label: "Asphalt Machine Parts" },
      { id: "backhoeLoaderParts", label: "Backhoe Loader Parts" },
      { id: "concretePumpParts", label: "Concrete Pump Parts" },
      { id: "railwayMachineParts", label: "Railway Machine Parts" },
      { id: "dozerParts", label: "Dozer Parts" },
      { id: "excavatorParts", label: "Excavator Parts" },
      { id: "paverParts", label: "Paver Parts" },
      { id: "forkliftParts", label: "Forklift Parts" },
      { id: "graderParts", label: "Grader Parts" },
      { id: "rockDrillParts", label: "Rock Drill Parts" },
      { id: "rockTruckSpareParts", label: "Rock Truck Spare Parts" },
      { id: "crusherParts", label: "Crusher Parts" },
      { id: "towerCraneParts", label: "Tower Crane Parts" },
      { id: "loaderParts", label: "Loader Parts" },
      { id: "mobileElevatorParts", label: "Mobile Elevator Parts" },
      { id: "mobileCrusherParts", label: "Mobile Crusher Parts" },
      { id: "mobileCraneParts", label: "Mobile Crane Parts" },
      { id: "cylinderParts", label: "Cylinder Parts" },
      { id: "drillingMachineParts", label: "Drilling Machine Parts" },
      { id: "telescopicLoaderParts", label: "Telescopic Loader Parts" },
      { id: "truckMixerParts", label: "Truck Mixer Parts" },
    ],
    tractors: [
      { id: "agrifarm", label: "Agrifarm" },
      { id: "agripower", label: "Agripower" },
      { id: "agromet", label: "Agromet" },
      { id: "agt", label: "AGT" },
      { id: "antonioCarraro", label: "Antonio Carraro" },
      { id: "arbos", label: "Arbos" },
      { id: "artrakSuperline", label: "Artrak Superline" },
      { id: "lion", label: "Lion" },
      { id: "virgo", label: "Virgo" },
      { id: "capitalCity", label: "Capital city" },
      { id: "bcs", label: "BCS" },
      { id: "belarus", label: "Belarus" },
      { id: "bmc", label: "BMC" },
      { id: "bull", label: "Bull" },
      { id: "bolgar", label: "Bolgar" },
      { id: "bolinderMunktell", label: "Bolinder-Munktell" },
      { id: "boron", label: "Boron" },
      { id: "bozok", label: "Bozok" },
      { id: "branson", label: "Branson" },
      { id: "captain", label: "Captain" },
      { id: "carraro", label: "Carraro" },
      { id: "caseIh", label: "Case IH" },
      { id: "cherry", label: "Cherry" },
      { id: "claas", label: "Claas" },
      { id: "davidBrown", label: "David Brown" },
      { id: "deutzFahr", label: "Deutz Fahr" },
      { id: "dexta", label: "Dexta" },
      { id: "ebro", label: "Ebro" },
      { id: "eich", label: "Eich" },
      { id: "eltar", label: "Eltar" },
      { id: "erkunt", label: "Erkunt" },
      { id: "farmtrac", label: "Farmtrac" },
      { id: "conqueror", label: "Conqueror" },
      { id: "fendt", label: "Fendt" },
      { id: "ferrari", label: "Ferrari" },
      { id: "fiat", label: "Fiat" },
      { id: "ford", label: "Ford" },
      { id: "photon", label: "Photon" },
      { id: "goldoni", label: "Goldoni" },
      { id: "grace", label: "Grace" },
      { id: "gutbrod", label: "Gutbrod" },
      { id: "guldner", label: "Guldner" },
      { id: "hanomag", label: "Hanomag" },
      { id: "blend", label: "Blend" },
      { id: "harsh", label: "Harsh" },
      { id: "calligrapher", label: "Calligrapher" },
      { id: "hema", label: "Hema" },
      { id: "holder", label: "Holder" },
      { id: "husqvarna", label: "Husqvarna" },
      { id: "hurlimann", label: "Hurlimann" },
      { id: "imt", label: "IMT" },
      { id: "international", label: "International" },
      { id: "irtem", label: "Irtem" },
      { id: "isbora", label: "Isbora" },
      { id: "jcb", label: "JCB" },
      { id: "jinma", label: "Jinma" },
      { id: "johnDeere", label: "John Deere" },
      { id: "kaan", label: "Kaan" },
      { id: "blackstone", label: "Blackstone" },
      { id: "katsu", label: "Katsu" },
      { id: "kioti", label: "Kioti" },
      { id: "kubota", label: "Kubota" },
      { id: "lamborghini", label: "Lamborghini" },
      { id: "landini", label: "Landini" },
      { id: "leyland", label: "Leyland" },
      { id: "lg", label: "LG" },
      { id: "lombardin", label: "Lombardin" },
      { id: "lsTractor", label: "LS Tractor" },
      { id: "mahindra", label: "Mahindra" },
      { id: "man", label: "MAN" },
      { id: "masseyFerguson", label: "Massey Ferguson" },
      { id: "masseyHarris", label: "Massey Harris" },
      { id: "mastash", label: "Mastash" },
      { id: "mccormick", label: "McCormick" },
      { id: "mehmetSimseker", label: "Mehmet Simseker" },
      { id: "mercedesBenz", label: "Mercedes Benz" },
      { id: "newHolland", label: "New Holland" },
      { id: "nibbi", label: "Nibbi" },
      { id: "nuoman", label: "Nuoman" },
      { id: "beet", label: "Beet" },
      { id: "perkis", label: "Perkis" },
      { id: "porsche", label: "Porsche" },
      { id: "renault", label: "Renault" },
      { id: "same", label: "Same" },
      { id: "solise", label: "Solise" },
      { id: "steyr", label: "Steyr" },
      { id: "sunway", label: "Sunway" },
      { id: "superMajor", label: "Super Major" },
      { id: "superStar", label: "Super Star" },
      { id: "tafe", label: "Tafe" },
      { id: "taral", label: "Taral" },
      { id: "towgo", label: "Towgo" },
      { id: "tumosan", label: "Tumosan" },
      { id: "turkishTractor", label: "Turkish Tractor" },
      { id: "tym", label: "TYM" },
      { id: "universal", label: "Universal" },
      { id: "ural", label: "Ural" },
      { id: "ursus", label: "Ursus" },
      { id: "uzel", label: "Uzel" },
      { id: "valpadan", label: "Valpadan" },
      { id: "valtra", label: "Valtra" },
      { id: "volvo", label: "Volvo" },
      { id: "rain", label: "Rain" },
      { id: "yanmar", label: "Yanmar" },
      { id: "yto", label: "YTO" },
      { id: "zetor", label: "Zetor" },
    ],
    soilCultivation: [
      { id: "treeRemovalMachine", label: "Tree Removal Machine" },
      { id: "tillerMachine", label: "Tiller Machine" },
      { id: "chiselSubsoiler", label: "Chisel & Subsoiler" },
      { id: "discHarrow", label: "Disc harrow" },
      { id: "castingRoller", label: "Casting Roller" },
      { id: "cultivator", label: "Cultivator" },
      { id: "laserLevelingSmoothing", label: "Laser Leveling & Smoothing" },
      { id: "mulchMachine", label: "Mulch Machine" },
      { id: "woodCrusherMachine", label: "Wood Crusher Machine" },
      { id: "plow", label: "Plow" },
      { id: "rotovator", label: "Rotovator" },
      { id: "mulcherMachine", label: "Mulcher Machine" },
      { id: "backMakingMachine", label: "Back Making Machine" },
      { id: "stoneCrusherMachine", label: "Stone Crusher Machine" },
      { id: "stoneCollectingMachine", label: "Stone Collecting Machine" },
      { id: "harrow", label: "Harrow" },
      { id: "soilLawnAeration", label: "Soil & Lawn Aeration" },
      { id: "earthAugerMachine", label: "Earth Auger Machine" },
      { id: "soilGrindingMachine", label: "Soil Grinding Machine" },
    ],
    harvestThresh: [
      { id: "harvester", label: "Harvester" },
      { id: "treeShakingMachine", label: "Tree Shaking Machine" },
      { id: "sunflowerHarvestTray", label: "Sunflower Harvest Tray" },
      {
        id: "sunflowerHarvesterPicking",
        label: "Sunflower Harvester & Picki...",
      },
      { id: "balerMachine", label: "Baler Machine" },
      { id: "bicerbaglar", label: "Bicerbaglar" },
      { id: "gradingMachine", label: "Grading Machine" },
      { id: "cottonGinMachine", label: "Cotton Gin Machine" },
      { id: "tomatoHarvestingMachine", label: "Tomato Harvesting Machine" },
      {
        id: "hazelnutHarvesterCollecting",
        label: "Hazelnut Harvester & Collec...",
      },
      { id: "peanutHarvester", label: "Peanut Harvester" },
      { id: "threshingMachine", label: "Threshing Machine" },
      { id: "pumpkinHarvester", label: "Pumpkin Harvester" },
      { id: "dryer", label: "Dryer" },
      { id: "fruitOlivePicking", label: "Fruit & Olive Picking" },
      { id: "cornHarvestTray", label: "Corn Harvest Tray" },
      { id: "cottonPickingMachine", label: "Cotton Picking Machine" },
      { id: "sugarBeetHarvester", label: "Sugar Beet Harvester" },
      { id: "potatoOnionDigging", label: "Potato & Onion Digging" },
      { id: "riceHarvester", label: "Rice Harvester" },
      { id: "tasselCuttingMachine", label: "Tassel Cutting Machine" },
      { id: "hayMachine", label: "Hay Machine" },
      { id: "silageMachine", label: "Silage Machine" },
      { id: "silagePackingMachine", label: "Silage Packing Machine" },
      { id: "peelingMachine", label: "Peeling Machine" },
      { id: "seedScreeningMachine", label: "Seed Screening Machine" },
      { id: "oliveSievingMachine", label: "Olive Sieving Machine" },
    ],
    plantCare: [
      { id: "pruningMachine", label: "Pruning Machine" },
      { id: "meadowLawnGrassMowing", label: "Meadow, Lawn & Grass Mow..." },
      { id: "sickleScytheMachine", label: "Sickle & Scythe Machine" },
      { id: "pelletMachine", label: "Pellet Machine" },
      { id: "preparingSawdust", label: "Preparing Sawdust" },
      { id: "blowingCollectingMachine", label: "Blowing Collecting Machine" },
      {
        id: "leafBranchShredderMachine",
        label: "Leaf & Branch Shredder Mac...",
      },
    ],
    plantingSowing: [
      { id: "seedingMachine", label: "Seeding Machine" },
      { id: "grainPlantingDrill", label: "Grain Planting Drill" },
      { id: "potatoOnionBread", label: "Potato & Onion Bread" },
      { id: "tobaccoPlantingMachine", label: "Tobacco Planting Machine" },
    ],
    fertilization: [
      {
        id: "fertilizerSpreadingSpreader",
        label: "Fertilizer Spreading & Sprea...",
      },
      { id: "fertilizerMixer", label: "Fertilizer Mixer" },
      { id: "fertilizerDryer", label: "Fertilizer Dryer" },
      { id: "fertilizerCrushing", label: "Fertilizer Crushing" },
      { id: "fertilizerPump", label: "Fertilizer Pump" },
      { id: "manureSeparator", label: "Manure Separator" },
      { id: "manureScraper", label: "Manure Scraper" },
      { id: "compostMachine", label: "Compost Machine" },
    ],
    irrigation: [
      { id: "fertilizerTank", label: "Fertilizer Tank" },
      { id: "beetrootEngine", label: "Beetroot Engine" },
      { id: "irrigationMachine", label: "Irrigation Machine" },
      { id: "waterPumpMotor", label: "Water Pump & Motor" },
      { id: "waterTanker", label: "Water Tanker" },
    ],
    livestockFarming: [
      { id: "beekeepingSupplies", label: "Beekeeping Supplies" },
      { id: "petScratchingBrush", label: "Pet Scratching Brush" },
      {
        id: "animalSlaughterhouseEquipment",
        label: "Animal Slaughterhouse Equi...",
      },
      { id: "milkingMachine", label: "Milking Machine" },
      { id: "feedCrushingCrushing", label: "Feed Crushing & Crushing" },
      { id: "feedMixerMachine", label: "Feed Mixer Machine" },
      { id: "feedProductionMachine", label: "Feed Production Machine" },
      { id: "barnEquipment", label: "Barn Equipment" },
    ],
    transport: [
      { id: "trailer", label: "Trailer" },
      { id: "conveyorBeltScrew", label: "Conveyor, Belt & Screw" },
      { id: "logTractorCrane", label: "Log Tractor Crane" },
      { id: "cratesBaskets", label: "Crates & Baskets" },
    ],
    industrialMachinery: [
      { id: "woodFurniture", label: "Wood & Furniture" },
      { id: "packagingPacking", label: "Packaging & Packing" },
      { id: "glassPlasticChemicals", label: "Glass, Plastic & Chemicals" },
      { id: "food", label: "Food" },
      { id: "building", label: "Building" },
      { id: "printingAdvertising", label: "Printing & Advertising" },
      { id: "mining", label: "Mining" },
      { id: "metalworking", label: "Metalworking" },
      { id: "automotive", label: "Automotive" },
      { id: "textilesShoes", label: "Textiles & Shoes" },
      { id: "heatVentilation", label: "Heat & Ventilation" },
      { id: "sparePartsAccessories", label: "Spare Parts & Accessories" },
      { id: "bulkSales", label: "Bulk Sales" },
    ],
    industrialKitchen: [
      { id: "foodPreparation", label: "Food Preparation" },
      { id: "cookingEquipment", label: "Cooking Equipment" },
      { id: "foodCoolingStorage", label: "Food Cooling & Storage" },
      { id: "barCafeRestaurant", label: "Bar, Cafe & Restaurant" },
      { id: "patisserieBakery", label: "Patisserie & Bakery" },
      { id: "dishwasherCleaning", label: "Dishwasher & Cleaning" },
      { id: "sink", label: "Sink" },
      { id: "service", label: "Service" },
      { id: "mobileStalls", label: "Mobile Stalls" },
      { id: "bulkSales", label: "Bulk Sales" },
    ],
    industrialFurniture: [
      { id: "barNightclubFurniture", label: "Bar & Nightclub Furniture" },
      { id: "hospitalFurniture", label: "Hospital Furniture" },
      { id: "cafeRestaurantFurniture", label: "Cafe & Restaurant Furniture" },
      { id: "hotelFurniture", label: "Hotel Furniture" },
    ],
    industrialCleaning: [
      { id: "laundry", label: "Laundry" },
      { id: "disinfectionSystems", label: "Disinfection Systems" },
      { id: "carpetCleaning", label: "Carpet Cleaning" },
      { id: "washingSweeping", label: "Washing & Sweeping" },
      { id: "sparePartsAccessories", label: "Spare Parts & Accessories" },
      { id: "bulkSales", label: "Bulk Sales" },
    ],
    industrialHardware: [
      { id: "wood", label: "Wood" },
      { id: "building", label: "Building" },
      { id: "metal", label: "Metal" },
      { id: "jobSecurity", label: "Job security" },
      { id: "coolTools", label: "Cool Tools" },
      { id: "measuringInstruments", label: "Measuring Instruments" },
      { id: "microInstruments", label: "Micro Instruments" },
      { id: "smallHandTools", label: "Small Hand Tools" },
      { id: "pipeProcessingEquipment", label: "Pipe Processing Equipment" },
    ],
    transportStacking: [
      { id: "forklifts", label: "Forklifts" },
      { id: "terminalTractor", label: "Terminal Tractor" },
      { id: "liftingAttachments", label: "Lifting Attachments" },
      { id: "elevators", label: "Elevators" },
      {
        id: "scaffoldingFormworkSystems",
        label: "Scaffolding & Formwork Sys...",
      },
      { id: "scales", label: "Scales" },
      { id: "platforms", label: "Platforms" },
      { id: "palletTrucks", label: "Pallet trucks" },
      { id: "stackingMachines", label: "Stacking Machines" },
      { id: "escalator", label: "Escalator" },
      { id: "cratesBaskets", label: "Crates & Baskets" },
      { id: "cargoTransportCarts", label: "Cargo Transport Carts" },
    ],
    compressor: [
      { id: "reciprocating", label: "Reciprocating" },
      { id: "screwed", label: "Screwed" },
      { id: "lean", label: "Lean" },
      { id: "dryersFilters", label: "Dryers & Filters" },
      { id: "sparePartsAccessories", label: "Spare Parts & Accessories" },
    ],
    shelvingProductDisplay: [
      { id: "marketEquipment", label: "Market Equipment" },
      { id: "shelvesAisles", label: "Shelves and Aisles" },
      { id: "stands", label: "Stands" },
      {
        id: "showcasesCountersCabinets",
        label: "Showcases, Counters & Cab...",
      },
      { id: "showcaseMannequins", label: "Showcase Mannequins" },
      { id: "accessories", label: "Accessories" },
      { id: "bulkSales", label: "Bulk Sales" },
    ],
    tentAwningShutter: [
      { id: "industrialTents", label: "Industrial Tents" },
      { id: "awningTarpaulin", label: "Awning & Tarpaulin" },
      { id: "shuttersBlinds", label: "Shutters & Blinds" },
      { id: "photocellAutomaticDoor", label: "Photocell & Automatic Door" },
      { id: "fastPvcDoor", label: "Fast PVC Door" },
    ],
    containerCabin: [
      { id: "cabins", label: "Cabins" },
      { id: "containers", label: "Containers" },
    ],
    protectionShelterSystems: [
      { id: "earthquakePanicCabins", label: "Earthquake & Panic Cabins" },
      { id: "cbrnShelters", label: "CBRN Shelters" },
      { id: "mineRefugeChambers", label: "Mine Refuge Chambers" },
    ],
    generator: [
      { id: "gasoline", label: "Gasoline" },
      { id: "diesel", label: "Diesel" },
      { id: "lpgNaturalGas", label: "LPG & Natural Gas" },
      { id: "sparePartsAccessories", label: "Spare Parts & Accessories" },
    ],
    electricityEnergy: [
      { id: "alternator", label: "Alternator" },
      { id: "distributionTransformer", label: "Distribution Transformer" },
      { id: "electricMotors", label: "Electric Motors" },
      { id: "industrialElectronics", label: "Industrial Electronics" },
      { id: "inverter", label: "Inverter" },
      { id: "isolationTransformer", label: "Isolation Transformer" },
      { id: "compensationBoard", label: "Compensation Board" },
      { id: "reactors", label: "Reactors" },
      { id: "rectifiers", label: "Rectifiers" },
      { id: "switchgearMaterials", label: "Switchgear Materials" },
      { id: "chargeRegulator", label: "Charge Regulator" },
      { id: "voltageRegulator", label: "Voltage Regulator" },
    ],
    fuelProducts: [
      { id: "fuelPump", label: "Fuel Pump" },
      { id: "fuelTank", label: "Fuel Tank" },
      { id: "fillingGun", label: "Filling Gun" },
      { id: "lpgPump", label: "LPG Pump" },
      { id: "lpgTank", label: "LPG Tank" },
      { id: "counter", label: "Counter" },
    ],
  },
  level4: {
    forklifts: [
      { id: "forSale", label: "For sale" },
      { id: "forRent", label: "For rent" },
      { id: "partsAttachments", label: "Parts & Attachments" },
    ],
    asphaltMachine: [
    { id: "ammann", label: "Ammann" },
    { id: "askaleMachinery", label: "Askale Machinery" },
    { id: "astec", label: "Astec" },
    { id: "benninghoven", label: "Benninghoven" },
    { id: "bitelli", label: "Bitelli" },
    { id: "bobcat", label: "Bobcat" },
    { id: "bomag", label: "Bomag" },
    { id: "caterpillar", label: "Caterpillar" },
    { id: "constmach", label: "Constmach" },
    { id: "demag", label: "Demag" },
    { id: "dewalt", label: "Dewalt" },
    { id: "ditchWitch", label: "Ditch Witch" },
    { id: "dynapac", label: "Dynapac" },
    { id: "elibol", label: "Elibol" },
    { id: "eMak", label: "E-MAK" },
    { id: "esisanMachine", label: "Esisan Machine" },
    { id: "etnyre", label: "Etnyre" },
    { id: "faboMachinery", label: "Fabo Machinery" },
    { id: "fimak", label: "Fimak" },
    { id: "gehl", label: "Gehl" },
    { id: "hydromech", label: "Hydromech" },
    { id: "hydrotorque", label: "Hydrotorque" },
    { id: "ingersollRand", label: "Ingersoll Rand" },
    { id: "makita", label: "Makita" },
    { id: "marini", label: "Marini" },
    { id: "readerMachine", label: "Reader Machine" },
    { id: "palmTree", label: "Palm tree" },
    { id: "ridgid", label: "Ridgid" },
    { id: "roadtec", label: "Roadtec" },
    { id: "simak", label: "Simak" },
    { id: "simex", label: "Simex" },
    { id: "srtMachinery", label: "SRT Machinery" },
    { id: "stihl", label: "Stihl" },
    { id: "tesmec", label: "Tesmec" },
    { id: "vermeer", label: "Vermeer" },
    { id: "vogele", label: "Vögele" },
    { id: "wirtgen", label: "Wirtgen" },
    { id: "yoshimitsu", label: "Yoshimitsu" },
    { id: "other", label: "Other" }
],
backhoeLoader: [
    { id: "ace", label: "ACE" },
    { id: "asimato", label: "Asimato" },
    { id: "attack", label: "Attack" },
    { id: "avant", label: "Avant" },
    { id: "bagsan", label: "Bagsan" },
    { id: "virgo", label: "Virgo" },
    { id: "benati", label: "Benati" },
    { id: "bobcat", label: "Bobcat" },
    { id: "bull", label: "Bull" },
    { id: "case", label: "Case" },
    { id: "caterpillar", label: "Caterpillar" },
    { id: "cukurovaMachinery", label: "Cukurova Machinery" },
    { id: "daewoo", label: "Daewoo" },
    { id: "doosan", label: "Doosan" },
    { id: "ermak", label: "Ermak" },
    { id: "everun", label: "Everun" },
    { id: "fai", label: "FAI" },
    { id: "fermec", label: "Fermec" },
    { id: "fiatHitachi", label: "Fiat Hitachi" },
    { id: "fimax", label: "Fimax" },
    { id: "ford", label: "Ford" },
    { id: "forward", label: "Forward" },
    { id: "furukawa", label: "Furukawa" },
    { id: "gehl", label: "Gehl" },
    { id: "gonen", label: "Gonen" },
    { id: "hibold", label: "Hibold" },
    { id: "hydroLeader", label: "HydroLeader" },
    { id: "hydromech", label: "Hydromech" },
    { id: "hinowa", label: "Hinowa" },
    { id: "hitachi", label: "Hitachi" },
    { id: "hpsystems", label: "Hpsystems" },
    { id: "hyundai", label: "Hyundai" },
    { id: "ihi", label: "IHI" },
    { id: "index", label: "Index" },
    { id: "jcb", label: "JCB" },
    { id: "johnDeere", label: "John Deere" },
    { id: "kawasaki", label: "Kawasaki" },
    { id: "keskinova", label: "Keskinova" },
    { id: "komatsu", label: "Komatsu" },
    { id: "kramerAllrad", label: "Kramer Allrad" },
    { id: "kubota", label: "Kubota" },
    { id: "lgma", label: "LGMA" },
    { id: "liugong", label: "Liugong" },
    { id: "lonking", label: "Lonking" },
    { id: "manitech", label: "Manitech" },
    { id: "manitou", label: "Manitou" },
    { id: "masseyFerguson", label: "Massey Ferguson" },
    { id: "masta", label: "Masta" },
    { id: "maxbull", label: "Maxbull" },
    { id: "mdTrackJob", label: "MD-Track JOB" },
    { id: "mecalac", label: "Mecalac" },
    { id: "mereks", label: "Mereks" },
    { id: "mersan", label: "Mersan" },
    { id: "mst", label: "MST" },
    { id: "multione", label: "Multione" },
    { id: "neumeier", label: "Neumeier" },
    { id: "newHolland", label: "New Holland" },
    { id: "piMachine", label: "PI Machine" },
    { id: "polarWolverine", label: "Polar Wolverine" },
    { id: "puma", label: "Puma" },
    { id: "same", label: "Same" },
    { id: "samsung", label: "Samsung" },
    { id: "schaeff", label: "Schaeff" },
    { id: "sdlg", label: "SDLG" },
    { id: "sinomach", label: "Sinomach" },
    { id: "steyr", label: "Steyr" },
    { id: "sumitomo", label: "Sumitomo" },
    { id: "sunward", label: "Sunward" },
    { id: "tavol", label: "Tavol" },
    { id: "terex", label: "Terex" },
    { id: "torcon", label: "Torcon" },
    { id: "taurus", label: "Taurus" },
    { id: "tumosan", label: "Tumosan" },
    { id: "universal", label: "Universal" },
    { id: "venieri", label: "Venieri" },
    { id: "volvo", label: "Volvo" },
    { id: "wackerNeuson", label: "Wacker Neuson" },
    { id: "xcmg", label: "XCMG" },
    { id: "yanmar", label: "Yanmar" },
    { id: "ygs", label: "YGS" },
    { id: "yoshimitsu", label: "Yoshimitsu" },
    { id: "youtop", label: "Youtop" },
    { id: "other", label: "Other" }
],
articulatedDumper: [
    { id: "ausa", label: "Ausa" },
    { id: "bergman", label: "Bergman" },
    { id: "caterpillar", label: "Caterpillar" },
    { id: "hydroman", label: "Hydroman" },
    { id: "thwaites", label: "Thwaites" },
    { id: "truxta", label: "Truxta" },
    { id: "wackerNeuson", label: "Wacker Neuson" },
    { id: "other", label: "Other" }
],
concreteDistributor: [
    { id: "atabeyMachinery", label: "Atabey Machinery" },
    { id: "betonstar", label: "Betonstar" },
    { id: "boomMachine", label: "Boom Machine" },
    { id: "putzmeister", label: "Putzmeister" },
    { id: "royalmac", label: "Royalmac" },
    { id: "other", label: "Other" }
],
concretePump: [
    { id: "abmArtas", label: "ABM Artas" },
    { id: "arg", label: "ARG" },
    { id: "asea", label: "ASEA" },
    { id: "askam", label: "Askam" },
    { id: "concrete", label: "Concrete" },
    { id: "concreteMixer", label: "Concrete mixer" },
    { id: "betonstar", label: "Betonstar" },
    { id: "bmc", label: "BMC" },
    { id: "bms", label: "BMS" },
    { id: "boomMachine", label: "Boom Machine" },
    { id: "brinkmann", label: "Brinkmann" },
    { id: "carmix", label: "Carmix" },
    { id: "cifaa", label: "CIFAA" },
    { id: "daf", label: "Daf" },
    { id: "elba", label: "Elba" },
    { id: "everdigm", label: "Everdigm" },
    { id: "farya", label: "Farya" },
    { id: "ford", label: "Ford" },
    { id: "gurpomConstructionMachi", label: "Gurpom Construction Machi..." },
    { id: "hyundai", label: "Hyundai" },
    { id: "imer", label: "IMER" },
    { id: "junjin", label: "Junjin" },
    { id: "kcp", label: "KCP" },
    { id: "klein", label: "Klein" },
    { id: "man", label: "MAN" },
    { id: "mercedesBenz", label: "Mercedes Benz" },
    { id: "mayco", label: "Mayco" },
    { id: "normet", label: "Normet" },
    { id: "piMachine", label: "PI Machine" },
    { id: "putzmeister", label: "Putzmeister" },
    { id: "reich", label: "Reich" },
    { id: "renault", label: "Renault" },
    { id: "rety", label: "RETY" },
    { id: "royalmac", label: "Royalmac" },
    { id: "royalMachine", label: "Royal Machine" },
    { id: "scania", label: "Scania" },
    { id: "schwing", label: "Schwing" },
    { id: "sermac", label: "Sermac" },
    { id: "titan", label: "Titan" },
    { id: "turbosol", label: "Turbosol" },
    { id: "tunneling", label: "Tunneling" },
    { id: "volvo", label: "Volvo" },
    { id: "waitzinger", label: "Waitzinger" },
    { id: "zoomlion", label: "Zoomlion" },
    { id: "other", label: "Other" }
],
garbageCompactor:[
  { id: "bomag", label: "Bomag" },
  { id: "cat", label: "CAT" },
  { id: "hamart", label: "Hamart" },
],
railwayMachine: [
  { id: "harsco", label: "Harsco" },
  { id: "karshaw", label: "Karshaw" },
  { id: "plasserTheurer", label: "Plasser & Theurer" },
  { id: "other", label: "Other" }
],
dozer: [
    { id: "bobcat", label: "Bobcat" },
    { id: "bomag", label: "Bomag" },
    { id: "case", label: "Case" },
    { id: "caterpillar", label: "Caterpillar" },
    { id: "fiat", label: "Fiat" },
    { id: "furukawa", label: "Furukawa" },
    { id: "gmc", label: "GMC" },
    { id: "grammar", label: "Grammar" },
    { id: "hanomag", label: "Hanomag" },
    { id: "hydromech", label: "Hydromech" },
    { id: "hpsystems", label: "Hpsystems" },
    { id: "hyundai", label: "Hyundai" },
    { id: "jcb", label: "JCB" },
    { id: "keskinova", label: "Keskinova" },
    { id: "komatsu", label: "Komatsu" },
    { id: "liebherr", label: "Liebherr" },
    { id: "liugong", label: "Liugong" },
    { id: "masseyFerguson", label: "Massey Ferguson" },
    { id: "mecalac", label: "Mecalac" },
    { id: "mst", label: "MST" },
    { id: "neumeier", label: "Neumeier" },
    { id: "puma", label: "Puma" },
    { id: "shantui", label: "Shantui" },
    { id: "sinomach", label: "Sinomach" },
    { id: "sumitomo", label: "Sumitomo" },
    { id: "tavol", label: "Tavol" },
    { id: "taurus", label: "Taurus" },
    { id: "volvo", label: "Volvo" },
    { id: "other", label: "Other" }
],
excavatorBucket: [
    { id: "akerman", label: "Akerman" },
    { id: "alpha", label: "Alpha" },
    { id: "alpine", label: "Alpine" },
    { id: "asimato", label: "Asimato" },
    { id: "atlas", label: "Atlas" },
    { id: "belarus", label: "Belarus" },
    { id: "betlift", label: "Betlift" },
    { id: "bobcat", label: "Bobcat" },
    { id: "carter", label: "Carter" },
    { id: "case", label: "Case" },
    { id: "caterpillar", label: "Caterpillar" },
    { id: "cherry", label: "Cherry" },
    { id: "cukurovaMachinery", label: "Cukurova Machinery" },
    { id: "daemo", label: "Daemo" },
    { id: "daewoo", label: "Daewoo" },
    { id: "demag", label: "Demag" },
    { id: "develo", label: "Develo" },
    { id: "digdog", label: "Digdog" },
    { id: "doosan", label: "Doosan" },
    { id: "dooxin", label: "Dooxin" },
    { id: "itIsWorth", label: "It is worth" },
    { id: "eurocomach", label: "Eurocomach" },
    { id: "everun", label: "Everun" },
    { id: "faresinIndustries", label: "Faresin Industries" },
    { id: "fiatHitachi", label: "Fiat Hitachi" },
    { id: "fuchs", label: "Fuchs" },
    { id: "furukawa", label: "Furukawa" },
    { id: "gradall", label: "Gradall" },
    { id: "halla", label: "Halla" },
    { id: "hanix", label: "Hanix" },
    { id: "hanomag", label: "Hanomag" },
    { id: "hbm", label: "HBM" },
    { id: "hengwang", label: "hengwang" },
    { id: "hibold", label: "Hibold" },
    { id: "hydromech", label: "Hydromech" },
    { id: "hinowa", label: "Hinowa" },
    { id: "hitachi", label: "Hitachi" },
    { id: "hpsystems", label: "Hpsystems" },
    { id: "huaya", label: "huaya" },
    { id: "hydroteam", label: "Hydroteam" },
    { id: "hyundai", label: "Hyundai" },
    { id: "ihi", label: "IHI" },
    { id: "ihimer", label: "ihimer" },
    { id: "index", label: "Index" },
    { id: "jcb", label: "JCB" },
    { id: "jiahee", label: "Jiahee" },
    { id: "kaisan", label: "Kaisan" },
    { id: "kaiser", label: "Kaiser" },
    { id: "kato", label: "Kato" },
    { id: "kenrobogen", label: "Kenrobogen" },
    { id: "keskinova", label: "Keskinova" },
    { id: "kobelco", label: "Kobelco" },
    { id: "komatsu", label: "Komatsu" },
    { id: "kubota", label: "Kubota" },
    { id: "leite", label: "Leite" },
    { id: "liebherr", label: "Liebherr" },
    { id: "linkBelt", label: "Link Belt" },
    { id: "liugong", label: "Liugong" },
    { id: "lonking", label: "Lonking" },
    { id: "ltmg", label: "LTMG" },
    { id: "manitech", label: "Manitech" },
    { id: "marion", label: "Marion" },
    { id: "masta", label: "Masta" },
    { id: "maxpower", label: "Maxpower" },
    { id: "mecalac", label: "Mecalac" },
    { id: "mereks", label: "Mereks" },
    { id: "mst", label: "MST" },
    { id: "neumeier", label: "Neumeier" },
    { id: "newHolland", label: "New Holland" },
    { id: "arrow", label: "ARROW" },
    { id: "octopus", label: "Octopus" },
    { id: "qilu", label: "Qilu" },
    { id: "rhinoceros", label: "Rhinoceros" },
    { id: "rippa", label: "Rippa" },
    { id: "rkn", label: "RKN" },
    { id: "samsung", label: "Samsung" },
    { id: "sandwich", label: "Sandwich" },
    { id: "sany", label: "Sany" },
    { id: "sdlg", label: "SDLG" },
    { id: "sennebogen", label: "Sennebogen" },
    { id: "seram", label: "Seram" },
    { id: "shantui", label: "Shantui" },
    { id: "sinomach", label: "Sinomach" },
    { id: "solmec", label: "Solmec" },
    { id: "sumitomo", label: "Sumitomo" },
    { id: "sunward", label: "Sunward" },
    { id: "takeuchi", label: "Takeuchi" },
    { id: "terex", label: "Terex" },
    { id: "taurus", label: "Taurus" },
    { id: "vermeer", label: "Vermeer" },
    { id: "volvo", label: "volvo" },
    { id: "wackerNeuson", label: "Wacker Neuson" },
    { id: "walimac", label: "Walimac" },
    { id: "xcmg", label: "XCMG" },
    { id: "yanmar", label: "Yanmar" },
    { id: "ygs", label: "YGS" },
    { id: "yoshimitsu", label: "Yoshimitsu" },
    { id: "youtop", label: "Youtop" },
    { id: "yuchai", label: "Yuchai" },
    { id: "rise", label: "Rise" },
    { id: "zoomlion", label: "Zoomlion" },
    { id: "other", label: "Other" }
],
finisher: [
    { id: "abg", label: "ABG" },
    { id: "bitelli", label: "Bitelli" },
    { id: "bomag", label: "Bomag" },
    { id: "caterpillar", label: "Caterpillar" },
    { id: "cmi", label: "CMI" },
    { id: "demag", label: "Demag" },
    { id: "dynapac", label: "Dynapac" },
    { id: "geometryMachine", label: "Geometry Machine" },
    { id: "gomaco", label: "Gomaco" },
    { id: "imb", label: "IMB" },
    { id: "leeboy", label: "Leeboy" },
    { id: "massenza", label: "Massenza" },
    { id: "roadtec", label: "Roadtec" },
    { id: "somer", label: "Somer" },
    { id: "sumitomo", label: "Sumitomo" },
    { id: "terex", label: "Terex" },
    { id: "volvo", label: "Volvo" },
    { id: "vogele", label: "Vogele" },
    { id: "other", label: "Other" }
],
boredPileMachine: [
    { id: "bauer", label: "Bauer" },
    { id: "casagrande", label: "Casagrande" },
    { id: "cat", label: "CAT" },
    { id: "comacchio", label: "Comacchio" },
    { id: "delmag", label: "Delmag" },
    { id: "drasmec", label: "Drasmec" },
    { id: "drasMec", label: "Dras Mec" },
    { id: "egt", label: "EGT" },
    { id: "ems", label: "EMS" },
    { id: "enteco", label: "Enteco" },
    { id: "gayk", label: "Gayk" },
    { id: "inTheHutte", label: "In the Hutte" },
    { id: "imt", label: "IMT" },
    { id: "jintai", label: "jintai" },
    { id: "brothersHydraulics", label: "Brothers Hydraulics" },
    { id: "liebherr", label: "Liebherr" },
    { id: "mait", label: "Mait" },
    { id: "pauselli", label: "Pauselli" },
    { id: "piMachine", label: "Pi Machine" },
    { id: "sany", label: "Sany" },
    { id: "selcukMachine", label: "Selcuk Machine" },
    { id: "soilmec", label: "Soilmec" },
    { id: "sumitomo", label: "Sumitomo" },
    { id: "sunward", label: "Sunward" },
    { id: "techniwell", label: "Techniwell" },
    { id: "terex", label: "Terex" },
    { id: "titon", label: "Titon" },
    { id: "turkish", label: "Turkish" },
    { id: "tysim", label: "Tysim" },
    { id: "vermeer", label: "Vermeer" },
    { id: "xcmg", label: "Xcmg" },
    { id: "other", label: "Other" }
],
grader: [
    { id: "barford", label: "Barford" },
    { id: "bobcat", label: "Bobcat" },
    { id: "case", label: "Case" },
    { id: "caterpillar", label: "Caterpillar" },
    { id: "champion", label: "Champion" },
    { id: "dnc", label: "DNC" },
    { id: "dresser", label: "Dresser" },
    { id: "faunFrisch", label: "Faun Frisch" },
    { id: "flatallis", label: "Flatallis" },
    { id: "fiatHitachi", label: "Fiat Hitachi" },
    { id: "galion", label: "Galion" },
    { id: "hbmBomaq", label: "HBM-Bomaq" },
    { id: "huber", label: "Huber" },
    { id: "index", label: "Index" },
    { id: "jcb", label: "JCB" },
    { id: "kawasaki", label: "Kawasaki" },
    { id: "komatsu", label: "Komatsu" },
    { id: "liugong", label: "Liugong" },
    { id: "lokoma", label: "Lokoma" },
    { id: "mitsubishi", label: "Mitsubishi" },
    { id: "mke", label: "MKE" },
    { id: "neumeier", label: "Neumeier" },
    { id: "arrow", label: "ARROW" },
    { id: "piMachine", label: "Pi Machine" },
    { id: "sany", label: "Sany" },
    { id: "sdlg", label: "SDLG" },
    { id: "terex", label: "Terex" },
    { id: "vammas", label: "Vammas" },
    { id: "venieri", label: "Venieri" },
    { id: "volvo", label: "Volvo" },
    { id: "wabco", label: "Wabco" },
    { id: "xcmg", label: "XCMG" }
],
canalTrenchDigger: [
    { id: "bobcatTrencher", label: "Bobcat Trencher" },
    { id: "ditchWitch", label: "Ditch Witch" },
    { id: "johnDeere", label: "John Deere" },
    { id: "tesmec", label: "Tesmec" },
    { id: "toroTrencher", label: "Toro Trencher" },
    { id: "vermeerTrencher", label: "Vermeer Trencher" },
    { id: "other", label: "Other" }
],
snowmobile: [
    { id: "lmc", label: "LMC" },
    { id: "pistenbutty", label: "Pistenbutty" },
    { id: "prinoth", label: "Prinoth" },
    { id: "ratrac", label: "RATRAC" },
    { id: "srtMachinery", label: "SRT Machinery" },
    { id: "other", label: "Other" }
],
snowPlowTruck: [
    { id: "amkodor", label: "Amkodor" },
    { id: "areksan", label: "Areksan" },
    { id: "attack", label: "Attack" },
    { id: "mcculloch", label: "Mcculloch" },
    { id: "multione", label: "Multione" },
    { id: "mud", label: "Mud" },
    { id: "ngNurGroup", label: "NG Nur Group" },
    { id: "prinoth", label: "Prinoth" },
    { id: "srtMachinery", label: "SRT Machinery" },
    { id: "turkar", label: "Turkar" },
    { id: "ural", label: "Ural" },
    { id: "other", label: "Other" }
],
snowBlower: [
    { id: "alcohol", label: "Alcohol" },
    { id: "ariens", label: "ARIENS" },
    { id: "cadet", label: "Cadet" },
    { id: "honda", label: "Honda" },
    { id: "mtd", label: "MTD" },
    { id: "rotba", label: "Rotba" },
    { id: "schmidt", label: "Schmidt" },
    { id: "srtMachinery", label: "SRT Machinery" },
    { id: "other", label: "Other" }
],
rockDrillAnchor: [
    { id: "adelsan", label: "Adelsan" },
    { id: "ariman", label: "Ariman" },
    { id: "atlasCopco", label: "Atlas Copco" },
    { id: "brg", label: "BRG" },
    { id: "brokk", label: "Brokk" },
    { id: "casagrande", label: "Casagrande" },
    { id: "caterpillar", label: "Caterpillar" },
    { id: "cmb", label: "CMB" },
    { id: "comacchio", label: "Comacchio" },
    { id: "daedong", label: "Daedong" },
    { id: "daemo", label: "Daemo" },
    { id: "dAndA", label: "D and A" },
    { id: "dnb", label: "DNB" },
    { id: "drasMec", label: "Dras Mec" },
    { id: "egt", label: "EGT" },
    { id: "everdigm", label: "Everdigm" },
    { id: "fineOre", label: "Fine ore" },
    { id: "furukawa", label: "Furukawa" },
    { id: "gardnerDenver", label: "Gardner Denver" },
    { id: "gema", label: "Gema" },
    { id: "hydrosan", label: "Hydrosan" },
    { id: "hydrock", label: "Hydrock" },
    { id: "hydromech", label: "Hydromech" },
    { id: "hkm", label: "Hkm" },
    { id: "hyundai", label: "Hyundai" },
    { id: "indeco", label: "Indeco" },
    { id: "ingersollRand", label: "Ingersoll Rand" },
    { id: "jcb", label: "JCB" },
    { id: "jhbk", label: "JHBK" },
    { id: "junjin", label: "Junjin" },
    { id: "klemm", label: "Klemm" },
    { id: "komac", label: "Komac" },
    { id: "krupp", label: "Krupp" },
    { id: "manitech", label: "Manitech" },
    { id: "milwaukee", label: "Milwaukee" },
    { id: "mineMaster", label: "Mine Master" },
    { id: "montabert", label: "Montabert" },
    { id: "msb", label: "MSB" },
    { id: "mtb", label: "MTB" },
    { id: "npc", label: "NPC" },
    { id: "okada", label: "Okada" },
    { id: "ocd", label: "OCD" },
    { id: "proter", label: "Proter" },
    { id: "rammer", label: "Rammer" },
    { id: "sandwich", label: "Sandwich" },
    { id: "sebas", label: "SEBAS" },
    { id: "selcukMachine", label: "Selcuk Machine" },
    { id: "soilmec", label: "Soilmec" },
    { id: "soosan", label: "Soosan" },
    { id: "stener", label: "Stener" },
    { id: "stihl", label: "Stihl" },
    { id: "subjectTo", label: "Subject to" },
    { id: "tamrock", label: "Tamrock" },
    { id: "teksomak", label: "Teksomak" },
    { id: "toku", label: "Toku" },
    { id: "onTheBall", label: "On the ball" },
    { id: "vega", label: "Vega" },
    { id: "vermeer", label: "Vermeer" },
    { id: "other", label: "Other" }
],
rockTruck: [
    { id: "astra", label: "Astra" },
    { id: "malady", label: "Malady" },
    { id: "bell", label: "Bell" },
    { id: "bidgel", label: "Bidgel" },
    { id: "bmc", label: "BMC" },
    { id: "caterpillar", label: "Caterpillar" },
    { id: "camel", label: "Camel" },
    { id: "komatsu", label: "Komatsu" },
    { id: "mercedesBenz", label: "Mercedes Benz" },
    { id: "renault", label: "Renault" },
    { id: "terex", label: "Terex" },
    { id: "volvo", label: "Volvo" },
    { id: "other", label: "Other" }
],
crushingScreeningPlant: [
    { id: "akyurekMachine", label: "Akyürek Machine" },
    { id: "atlasCopco", label: "Atlas Copco" },
    { id: "ayemMachine", label: "AYEM MACHINE" },
    { id: "sparkle", label: "Sparkle" },
    { id: "betontasMachine", label: "BETONTAŞ MACHINE" },
    { id: "beyerMachine", label: "BEYER MACHINE" },
    { id: "boratas", label: "Borataş" },
    { id: "burayMakine", label: "Buray Makine" },
    { id: "burcelik", label: "Burcelik" },
    { id: "cesa", label: "Cesa" },
    { id: "constmach", label: "Constmach" },
    { id: "csbMachine", label: "CSB Machine" },
    { id: "steel", label: "Steel" },
    { id: "cimenlerMachine", label: "ÇİMENLER MACHINE" },
    { id: "dmMachine", label: "DM MACHINE" },
    { id: "dragon", label: "Dragon" },
    { id: "drgMachine", label: "DRG MACHINE" },
    { id: "entema", label: "Entema" },
    { id: "fabo", label: "Fabo" },
    { id: "effortMakina", label: "Effort Makina" },
    { id: "incomingMachine", label: "Incoming machine" },
    { id: "generalMachine", label: "General Machine" },
    { id: "gurbuzMachine", label: "Gürbüz Machine" },
    { id: "gursanMakina", label: "Gursan Makina" },
    { id: "ibrahimCimenMachinery", label: "İbrahim Çimen Machinery" },
    { id: "kiemann", label: "Kiemann" },
    { id: "koksallarMachine", label: "KOKSALLAR MACHINE" },
    { id: "miningMachine", label: "Mining machine" },
    { id: "mcCloskey", label: "McCloskey" },
    { id: "mega", label: "Mega" },
    { id: "work", label: "Work" },
    { id: "mesMakina", label: "Mes Makina" },
    { id: "metso", label: "Metso" },
    { id: "mkMachine", label: "Mk machine" },
    { id: "muka", label: "Muka" },
    { id: "mutatives", label: "Mutatives" },
    { id: "nace", label: "Nace" },
    { id: "nurGroup", label: "Nur Group" },
    { id: "ozKoksallarMachine", label: "Oz Koksallar Machine" },
    { id: "piMachine", label: "Pi Machine" },
    { id: "portafill", label: "Portafill" },
    { id: "powerscreen", label: "POWERSCREEN" },
    { id: "reachingTechnicalMachine", label: "Reaching Technical Machine" },
    { id: "sees", label: "Sees" },
    { id: "sernaden", label: "Sernaden" },
    { id: "srtMachinery", label: "SRT Machinery" },
    { id: "ifYouCarry", label: "If you carry" },
    { id: "terex", label: "Terex" },
    { id: "tutsanMachine", label: "Tutsan machine" },
    { id: "ugurMaki", label: "Uğur Maki" },
    { id: "yilmazlarMachine", label: "YILMAZLAR MACHINE" },
    { id: "other", label: "Other" }
],
loader: [
    { id: "ahlman", label: "Ahlman" },
    { id: "alpine", label: "Alpine" },
    { id: "lower", label: "LOWER" },
    { id: "ant", label: "ANT" },
    { id: "asimato", label: "Asimato" },
    { id: "attack", label: "Attack" },
    { id: "avant", label: "Avant" },
    { id: "bagsan", label: "Bagsan" },
    { id: "virgo", label: "Virgo" },
    { id: "benati", label: "Benati" },
    { id: "bobcat", label: "Bobcat" },
    { id: "case", label: "Case" },
    { id: "caterpillar", label: "Caterpillar" },
    { id: "chengGong", label: "Cheng Gong" },
    { id: "cukurovaMachinery", label: "Cukurova Machinery" },
    { id: "daewoo", label: "Daewoo" },
    { id: "develo", label: "Develo" },
    { id: "doosan", label: "Doosan" },
    { id: "dooxin", label: "Dooxin" },
    { id: "eurocomach", label: "Eurocomach" },
    { id: "everun", label: "Everun" },
    { id: "fai", label: "FAI" },
    { id: "mouseTongue", label: "Mouse tongue" },
    { id: "ferguson", label: "Ferguson" },
    { id: "fermec", label: "Fermec" },
    { id: "fiatallis", label: "Fiatallis" },
    { id: "fimax", label: "Fimax" },
    { id: "forward", label: "Forward" },
    { id: "furukawa", label: "Furukawa" },
    { id: "gehl", label: "Gehl" },
    { id: "giant", label: "Giant" },
    { id: "gonen", label: "Gonen" },
    { id: "gunmak", label: "Gunmak" },
    { id: "hama", label: "Hama" },
    { id: "hanix", label: "Hanix" },
    { id: "hanomag", label: "Hanomag" },
    { id: "hercules", label: "Hercules" },
    { id: "hibold", label: "Hibold" },
    { id: "hydromech", label: "Hydromech" },
    { id: "hitachi", label: "Hitachi" },
    { id: "hpsystems", label: "Hpsystems" },
    { id: "hyundai", label: "Hyundai" },
    { id: "index", label: "Index" },
    { id: "jcb", label: "JCB" },
    { id: "jci", label: "JCI" },
    { id: "jiahee", label: "Jiahee" },
    { id: "head", label: "Head" },
    { id: "kaffaMachinery", label: "Kaffa Machinery" },
    { id: "kato", label: "Kato" },
    { id: "kawasaki", label: "Kawasaki" },
    { id: "kobelco", label: "Kobelco" },
    { id: "komatsu", label: "Komatsu" },
    { id: "konenka", label: "Konenka" },
    { id: "kramer", label: "Kramer" },
    { id: "lamborghini", label: "Lamborghini" },
    { id: "lgma", label: "LGMA" },
    { id: "liebherr", label: "Liebherr" },
    { id: "liugong", label: "Liugong" },
    { id: "locust", label: "Locust" },
    { id: "lonking", label: "Lonking" },
    { id: "manitech", label: "Manitech" },
    { id: "manitou", label: "Manitou" },
    { id: "masseyFerguson", label: "Massey Ferguson" },
    { id: "mecalac", label: "Mecalac" },
    { id: "mereks", label: "Mereks" },
    { id: "purplebark", label: "Purplebark" },
    { id: "mst", label: "MST" },
    { id: "multione", label: "Multione" },
    { id: "mustang", label: "Mustang" },
    { id: "neumeier", label: "Neumeier" },
    { id: "polarWolverine", label: "Polar Wolverine" },
    { id: "puma", label: "Puma" },
    { id: "samsung", label: "Samsung" },
    { id: "sandwich", label: "Sandwich" },
    { id: "sany", label: "Sany" },
    { id: "heSaved", label: "He saved" },
    { id: "schaeff", label: "Schaeff" },
    { id: "sdlg", label: "SDLG" },
    { id: "shantui", label: "Shantui" },
    { id: "sunward", label: "Sunward" },
    { id: "taian", label: "Taian" },
    { id: "takeuchi", label: "Takeuchi" },
    { id: "tavol", label: "Tavol" },
    { id: "tcm", label: "TCM" },
    { id: "terex", label: "Terex" },
    { id: "torcon", label: "Torcon" },
    { id: "toro", label: "Toro" },
    { id: "taurus", label: "Taurus" },
    { id: "universal", label: "Universal" },
    { id: "usus", label: "Usus" },
    { id: "venieri", label: "Venieri" },
    { id: "volvo", label: "Volvo" },
    { id: "wackerNeuson", label: "Wacker Neuson" },
    { id: "xcmg", label: "XCMG" },
    { id: "yanmar", label: "Yanmar" },
    { id: "ygs", label: "YGS" },
    { id: "yineng", label: "YINENG" },
    { id: "youtop", label: "Youtop" },
    { id: "yuchai", label: "Yuchai" },
    { id: "other", label: "Other" }
],
mobileCrusher: [
    { id: "akinMachinery", label: "Akin Machinery" },
    { id: "slang", label: "Slang" },
    { id: "atlasCopco", label: "Atlas Copco" },
    { id: "sparkle", label: "Sparkle" },
    { id: "betcon", label: "Betcon" },
    { id: "beyerMachine", label: "Beyer Machine" },
    { id: "boratasMachinery", label: "Borataş Machinery" },
    { id: "burcelik", label: "Burcelik" },
    { id: "constmach", label: "Constmach" },
    { id: "steelMachinery", label: "Steel Machinery" },
    { id: "grassMachine", label: "Grass Machine" },
    { id: "breakwater", label: "Breakwater" },
    { id: "demirstarMachinery", label: "DemirStar Machinery" },
    { id: "dmMachinery", label: "DM Machinery" },
    { id: "dragonMachine", label: "Dragon Machine" },
    { id: "drgMachine", label: "DRG MACHINE" },
    { id: "entema", label: "Entema" },
    { id: "extec", label: "Extec" },
    { id: "faboMachinery", label: "Fabo Machinery" },
    { id: "fsMachinery", label: "FS Machinery" },
    { id: "effortMakina", label: "Effort Makina" },
    { id: "generalMachinery", label: "General Machinery" },
    { id: "youAreAGunaysan", label: "You are a Gunaysan" },
    { id: "robust", label: "Robust" },
    { id: "gursanMachinery", label: "Gursan Machinery" },
    { id: "harti", label: "Harti" },
    { id: "kensanMachinery", label: "Kensan Machinery" },
    { id: "kleemann", label: "Kleemann" },
    { id: "koksallarMachinery", label: "Koksallar Machinery" },
    { id: "mcCloskey", label: "McCloskey" },
    { id: "mesko", label: "Mesko" },
    { id: "metso", label: "Metso" },
    { id: "mkMachine", label: "Mk machine" },
    { id: "muka", label: "Muka" },
    { id: "kitchener", label: "Kitchener" },
    { id: "nace", label: "Nace" },
    { id: "newcomen", label: "Newcomen" },
    { id: "ozyurt", label: "Ozyurt" },
    { id: "piMachine", label: "Pi Machine" },
    { id: "pioneer", label: "Pioneer" },
    { id: "polygonmach", label: "Polygonmach" },
    { id: "portafill", label: "Portafill" },
    { id: "powerScreen", label: "PowerScreen" },
    { id: "rockster", label: "Rockster" },
    { id: "rubbleMaster", label: "Rubble Master" },
    { id: "sees", label: "Sees" },
    { id: "sandwich", label: "Sandwich" },
    { id: "semak", label: "Semak" },
    { id: "sermaden", label: "Sermaden" },
    { id: "srtMachinery", label: "SRT Machinery" },
    { id: "suerMachinery", label: "Suer Machinery" },
    { id: "ifYouCarry", label: "If you carry" },
    { id: "tekelMachinery", label: "Tekel Machinery" },
    { id: "terexFinlay", label: "Terex-Finlay" },
    { id: "terexPegson", label: "Terex-Pegson" },
    { id: "tutsanMachinery", label: "Tutsan Machinery" },
    { id: "ugurMachinery", label: "Ugur Machinery" },
    { id: "other", label: "Other" }
],
cylinder: [
    { id: "amman", label: "Amman" },
    { id: "asimato", label: "Asimato" },
    { id: "bagsan", label: "Bagsan" },
    { id: "bitelli", label: "Bitelli" },
    { id: "bomag", label: "Bomag" },
    { id: "brooch", label: "Brooch" },
    { id: "caterpillar", label: "Caterpillar" },
    { id: "cukurovaMachinery", label: "Cukurova Machinery" },
    { id: "dynapac", label: "Dynapac" },
    { id: "hamm", label: "Hamm" },
    { id: "hydromech", label: "Hydromech" },
    { id: "hydrotorque", label: "Hydrotorque" },
    { id: "hmsHarman", label: "HMS Harman" },
    { id: "hyundai", label: "Hyundai" },
    { id: "index", label: "Index" },
    { id: "ingersollrand", label: "Ingersollrand" },
    { id: "jcb", label: "JCB" },
    { id: "keskinova", label: "Keskinova" },
    { id: "komatsu", label: "Komatsu" },
    { id: "labrero", label: "Labrero" },
    { id: "liuGong", label: "Liu Gong" },
    { id: "low", label: "LOW" },
    { id: "marini", label: "Marini" },
    { id: "mdTrackJob", label: "MD-Track JOB" },
    { id: "mecalac", label: "Mecalac" },
    { id: "verse", label: "Verse" },
    { id: "mst", label: "MST" },
    { id: "neumeier", label: "Neumeier" },
    { id: "ozmak", label: "Ozmak" },
    { id: "palmTree", label: "Palm tree" },
    { id: "saka", label: "Saka" },
    { id: "sany", label: "Sany" },
    { id: "sdlg", label: "SDLG" },
    { id: "srtMachinery", label: "SRT Machinery" },
    { id: "sta", label: "STA" },
    { id: "vibromax", label: "Vibromax" },
    { id: "vibrotech", label: "Vibrotech" },
    { id: "volvo", label: "Volvo" },
    { id: "wacker", label: "Wacker" },
    { id: "wackerNeuson", label: "Wacker Neuson" },
    { id: "xcmg", label: "XCMG" },
    { id: "youtop", label: "Youtop" },
    { id: "other", label: "Other" }
],
telescopicLoader: [
    { id: "ausa", label: "Ausa" },
    { id: "bagsan", label: "Bagsan" },
    { id: "bobcat", label: "Bobcat" },
    { id: "case", label: "Case" },
    { id: "cat", label: "CAT" },
    { id: "caterpillar", label: "Caterpillar" },
    { id: "claas", label: "Claas" },
    { id: "clark", label: "Clark" },
    { id: "dieci", label: "Dieci" },
    { id: "everun", label: "Everun" },
    { id: "youAreAMouse", label: "You are a mouse" },
    { id: "genie", label: "Genie" },
    { id: "giant", label: "Giant" },
    { id: "haluotte", label: "Haluotte" },
    { id: "heli", label: "Heli" },
    { id: "hpsystems", label: "Hpsystems" },
    { id: "hyster", label: "Hyster" },
    { id: "jcb", label: "JCB" },
    { id: "jlg", label: "JLG" },
    { id: "kaffaMachinery", label: "Kaffa Machinery" },
    { id: "carprocess", label: "Carprocess" },
    { id: "lull", label: "Lull" },
    { id: "komatsu", label: "Komatsu" },
    { id: "keskinova", label: "Keskinova" },
    { id: "kramer", label: "Kramer" },
    { id: "lmgmg", label: "Lmgmg" },
    { id: "ltmg", label: "LTMG" },
    { id: "magni", label: "Magni" },
    { id: "manitou", label: "Manitou" },
    { id: "masseyFerguson", label: "Massey Ferguson" },
    { id: "masta", label: "Masta" },
    { id: "mecalac", label: "Mecalac" },
    { id: "merlo", label: "Merlo" },
    { id: "mst", label: "MST" },
    { id: "newHolland", label: "New Holland" },
    { id: "ormia", label: "Ormia" },
    { id: "sany", label: "Sany" },
    { id: "steiner", label: "Steiner" },
    { id: "sunward", label: "Sunward" },
    { id: "terex", label: "Terex" },
    { id: "torcon", label: "Torcon" },
    { id: "taurus", label: "Taurus" },
    { id: "wackerNeuson", label: "Wacker Neuson" },
    { id: "yoshimitsu", label: "Yoshimitsu" },
    { id: "youtop", label: "Youtop" },
    { id: "other", label: "Other" }
],
 transmixer: [
  { id: "askam", label: "Askam" },
  { id: "betamix", label: "Betamix" },
  { id: "bmc", label: "BMC" },
  { id: "carmix", label: "Carmix" },
  { id: "daf", label: "DAF" },
  { id: "dieci", label: "Dieci" },
  { id: "dodge", label: "Dodge" },
  { id: "ermak", label: "Ermak" },
  { id: "fargo", label: "Fargo" },
  { id: "fiori", label: "Fiori" },
  { id: "ford", label: "Ford" },
  { id: "hibold", label: "Hibold" },
  { id: "iveco", label: "Iveco" },
  { id: "man", label: "MAN" },
  { id: "mercedes-benz", label: "Mercedes Benz" },
  { id: "merlo", label: "Merlo" },
  { id: "renault", label: "Renault" },
  { id: "samsung", label: "Samsung" },
  { id: "scania", label: "Scania" },
  { id: "volvo", label: "Volvo" },
  { id: "other", label: "Other" },
],
asphaltMachineRent:[
  { id: "bobcat", label: "Bobcat" },
  { id: "bomag", label: "BOMAG" },
  { id: "cat", label: "CAT" },
  { id: "gehl", label: "Gehl" },
  { id: "srt-machinery", label: "SRT Machinery" },
  { id: "wirtgen", label: "Wirtgen" },
  { id: "other", label: "Other" }
],
backhoeLoaderRent: [
  { id: "bobcat", label: "Bobcat" },
  { id: "case", label: "Case" },
  { id: "caterpillar", label: "Caterpillar" },
  { id: "hydromech", label: "Hydromech" },
  { id: "hpsystems", label: "Hpsystems" },
  { id: "jcb", label: "JCB" },
  { id: "komatsu", label: "Komatsu" },
  { id: "lgma", label: "LGMA" },
  { id: "mecalac", label: "Mecalac" },
  { id: "mst", label: "MST" },
  { id: "neumeier", label: "Neumeier" },
  { id: "newholland", label: "New Holland" },
  { id: "pimachine", label: "Pi Machine" },
  { id: "sdlg", label: "SDLG" },
  { id: "sinomach", label: "Sinomach" },
  { id: "tavol", label: "Tavol" },
  { id: "terex", label: "Terex" },
  { id: "volvo", label: "Volvo" },
  { id: "other", label: "Other" }
],
concretePumpRent: [
  { id: "askam", label: "Askam" },
  { id: "concretemixer", label: "Concrete mixer" },
  { id: "betonstar", label: "Betonstar" },
  { id: "bmc", label: "BMC" },
  { id: "bms", label: "BMS" },
  { id: "boommachine", label: "Boom Machine" },
  { id: "cifaa", label: "CIFAA" },
  { id: "daf", label: "Daf" },
  { id: "everdigm", label: "Everdigm" },
  { id: "farya", label: "Farya" },
  { id: "ford", label: "Ford" },
  { id: "gurpomconstructionmachine", label: "Gurpom Construction Machine" },
  { id: "junjin", label: "Junjin" },
  { id: "kcp", label: "KCP" },
  { id: "klein", label: "Klein" },
  { id: "man", label: "MAN" },
  { id: "mercedesbenz", label: "Mercedes Benz" },
  { id: "pimachine", label: "Pi Machine" },
  { id: "putzmeister", label: "Putzmeister" },
  { id: "reich", label: "Reich" },
  { id: "renault", label: "Renault" },
  { id: "rety", label: "RETY" },
  { id: "scania", label: "Scania" },
  { id: "schwing", label: "Schwing" },
  { id: "sermac", label: "Sermac" },
  { id: "titan", label: "Titan" },
  { id: "tunneling", label: "Tunneling" },
  { id: "volvo", label: "Volvo" },
  { id: "waitzinger", label: "Waitzinger" },
  { id: "other", label: "Other" }
],
dozerRent: [
  { id: "case", label: "CASE" },
  { id: "cat", label: "CAT" },
  { id: "fiat", label: "Fiat" },
  { id: "fiatallis", label: "Fiatallis" },
  { id: "furukawa", label: "Furukawa" },
  { id: "grammer", label: "Grammer" },
  { id: "hpsystems", label: "Hpsystems" },
  { id: "jcb", label: "JCB" },
  { id: "komatsu", label: "Komatsu" },
  { id: "liebherr", label: "Liebherr" },
  { id: "masseyferguson", label: "Massey Ferguson" },
  { id: "mecalac", label: "Mecalac" },
  { id: "neumeier", label: "Neumeier" },
  { id: "shantui", label: "Shantui" },
  { id: "sinomach", label: "Sinomach" },
  { id: "tavol", label: "Tavol" },
  { id: "other", label: "Other" }
],
excavatorBucketRent: [
  { id: "asimato", label: "Asimato" },
  { id: "belarus", label: "Belarus" },
  { id: "bobcat", label: "Bobcat" },
  { id: "carter", label: "Carter" },
  { id: "case", label: "Case" },
  { id: "cat", label: "Cat" },
  { id: "caterpillar", label: "Caterpillar" },
  { id: "cukurova", label: "Cukurova" },
  { id: "daewoo", label: "Daewoo" },
  { id: "deveto", label: "Deveto" },
  { id: "doosan", label: "Doosan" },
  { id: "hibold", label: "Hibold" },
  { id: "hydromech", label: "Hydromech" },
  { id: "hitachi", label: "Hitachi" },
  { id: "hpsystems", label: "Hpsystems" },
  { id: "hydroteam", label: "Hydroteam" },
  { id: "hyundai", label: "Hyundai" },
  { id: "ichimer", label: "Ichimer" },
  { id: "jcb", label: "JCB" },
  { id: "kaisan", label: "Kaisan" },
  { id: "lg", label: "LG" },
  { id: "kobelco", label: "Kobelco" },
  { id: "komatsu", label: "Komatsu" },
  { id: "kubota", label: "Kubota" },
  { id: "liebherr", label: "Liebherr" },
  { id: "liugong", label: "Liugong" },
  { id: "ltmg", label: "LTMG" },
  { id: "maxpower", label: "Maxpower" },
  { id: "mecalac", label: "Mecalac" },
  { id: "mst", label: "MST" },
  { id: "neumeier", label: "Neumeier" },
  { id: "newholland", label: "New Holland" },
  { id: "samsung", label: "Samsung" },
  { id: "sany", label: "Sany" },
  { id: "sdlg", label: "SDLG" },
  { id: "sennebogen", label: "Sennebogen" },
  { id: "shantui", label: "Shantui" },
  { id: "srtmachinery", label: "SRT Machinery" },
  { id: "sumitomo", label: "Sumitomo" },
  { id: "sunward", label: "Sunward" },
  { id: "takeuchi", label: "Takeuchi" },
  { id: "volvo", label: "Volvo" },
  { id: "wackerneuson", label: "Wacker Neuson" },
  { id: "xcmg", label: "XCMG" },
  { id: "yanmar", label: "Yanmar" },
  { id: "ygs", label: "YGS" },
  { id: "zoomlion", label: "Zoomlion" },
  { id: "other", label: "Other" }
],
finisherRent:[
  { id: "caterpillar", label: "Caterpillar" },
  { id: "dynapac", label: "Dynapac" },
  { id: "vogele", label: "Vogele" },
  { id: "other", label: "Other" }
],
boredPileMachineRent: [
  { id: "casagrande", label: "Casagrande" },
  { id: "drasmec", label: "Dras Mec" },
  { id: "gayk", label: "Gayk" },
  { id: "liebherr", label: "Liebherr" },
  { id: "mait", label: "Mait" },
  { id: "soilmec", label: "Soilmec" },
  { id: "turkish", label: "Turkish" },
  { id: "xcmg", label: "XCMG" },
  { id: "other", label: "Other" }
],
graderRent: [
  { id: "caterpillar", label: "Caterpillar" },
  { id: "champion", label: "Champion" },
  { id: "fiathitachi", label: "Fiat Hitachi" },
  { id: "galion", label: "Galion" },
  { id: "komatsu", label: "Komatsu" },
  { id: "neumeier", label: "Neumeier" },
  { id: "sdlg", label: "SDLG" },
  { id: "volvo", label: "Volvo" },
  { id: "zoomlion", label: "Zoomlion" },
  { id: "other", label: "Other" }
],
snowPlowTruckRent: [
    { id: "lmc", label: "LMC" },
    { id: "ng nur group", label: "NG Nur Group" },
    { id: "srt machinery", label: "SRT Machinery" },
    { id: "other", label: "Other" }
],
rockDrill: [
    { id: "atlas copco", label: "Atlas Copco" },
    { id: "furukawa", label: "Furukawa" },
    { id: "sandvik", label: "Sandvik" },
    { id: "steiner", label: "Steiner" },
    { id: "tamrock", label: "Tamrock" },
    { id: "other", label: "Other" }
],
rockTruckRent: [
    { id: "bidgel", label: "Bidgel" },
    { id: "bmc", label: "BMC" },
    { id: "caterpillar", label: "Caterpillar" },
    { id: "komatsu", label: "Komatsu" },
    { id: "man", label: "MAN" },
    { id: "tatras", label: "Tatras" },
    { id: "terex", label: "Terex" },
    { id: "volvo", label: "Volvo" },
    { id: "other", label: "Other" }
],
crushingScreeningPlantRent: [
    { id: "beyer", label: "Beyer" },
    { id: "boratas", label: "Boratas" },
    { id: "dragon", label: "Dragon" },
    { id: "gursan machinery", label: "Gursan Machinery" },
    { id: "klesmann", label: "Klesmann" },
    { id: "mccloskey", label: "McCloskey" },
    { id: "muka", label: "Muka" },
    { id: "portafill", label: "Portafill" },
    { id: "power screen", label: "Power screen" },
    { id: "saes", label: "Saes" },
    { id: "srt machinery", label: "SRT Machinery" },
    { id: "terex", label: "Terex" },
    { id: "wirtgen", label: "Wirtgen" },
    { id: "other", label: "Other" }
],
loaderRent: [
    { id: "alpine", label: "Alpine" },
    { id: "avant", label: "Avant" },
    { id: "bobcat", label: "Bobcat" },
    { id: "case", label: "Case" },
    { id: "caterpillar", label: "Caterpillar" },
    { id: "cukurova", label: "Cukurova" },
    { id: "daewoo", label: "Daewoo" },
    { id: "develo", label: "Develo" },
    { id: "gehl", label: "Gehl" },
    { id: "hercules", label: "Hercules" },
    { id: "hitachi", label: "Hitachi" },
    { id: "hpsystems", label: "Hpsystems" },
    { id: "hyundai", label: "Hyundai" },
    { id: "jcb", label: "JCB" },
    { id: "kawasaki", label: "Kawasaki" },
    { id: "komatsu", label: "Komatsu" },
    { id: "liugong", label: "Liugong" },
    { id: "mecalac", label: "Mecalac" },
    { id: "neumeier", label: "Neumeier" },
    { id: "new holland", label: "New Holland" },
    { id: "sdlg", label: "SDLG" },
    { id: "shantui", label: "Shantui" },
    { id: "tavol", label: "Tavol" },
    { id: "volvo", label: "Volvo" },
    { id: "xcmg", label: "XCMG" },
    { id: "yineng", label: "Yineng" },
    { id: "other", label: "Other" }
],
mobileCrusherRent: [
    { id: "atlas copco", label: "Atlas Copco" },
    { id: "beyer", label: "Beyer" },
    { id: "boratas", label: "Boratas" },
    { id: "burcelik", label: "Burcelik" },
    { id: "demirstar machinery", label: "DemirStar Machinery" },
    { id: "dragon", label: "Dragon" },
    { id: "entema", label: "Entema" },
    { id: "extec", label: "Extec" },
    { id: "fabo machinery", label: "Fabo Machinery" },
    { id: "general machinery", label: "General Machinery" },
    { id: "gursan machinery", label: "Gursan Machinery" },
    { id: "hartl", label: "Hartl" },
    { id: "klesmann", label: "Klesmann" },
    { id: "mccloskey", label: "McCloskey" },
    { id: "metso", label: "Metso" },
    { id: "muka", label: "Muka" },
    { id: "neuson hydrotec", label: "Neuson Hydrotec" },
    { id: "ozyurt", label: "Ozyurt" },
    { id: "pi machine", label: "Pi Machine" },
    { id: "portafill", label: "Portafill" },
    { id: "rockster", label: "Rockster" },
    { id: "sandwich", label: "Sandwich" },
    { id: "srt machinery", label: "SRT Machinery" },
    { id: "terex-finlay", label: "Terex-Finlay" },
    { id: "tutsan machinery", label: "Tutsan Machinery" },
    { id: "other", label: "Other" }
]
  },
  level5: {
    forSale: [
      { id: "ahilift", label: "Ahilift" },
      { id: "alpha", label: "Alpha" },
      { id: "alimar", label: "Alimar" },
      { id: "allisChalmers", label: "Allis Chalmers" },
      { id: "anadolulift", label: "Anadolulift" },
      { id: "aPower", label: "A-Power" },
      { id: "arlift", label: "Arlift" },
      { id: "armani", label: "Armani" },
      { id: "asimato", label: "Asimato" },
      { id: "atf", label: "ATF" },
      { id: "atlas", label: "Atlas" },
      { id: "athleteTrucks", label: "Athlete Trucks" },
      { id: "attack", label: "Attack" },
      { id: "ausa", label: "Ausa" },
      { id: "bagsan", label: "Bagsan" },
      { id: "balkancar", label: "Balkancar" },
      { id: "baoli", label: "baoli" },
      { id: "baumann", label: "Baumann" },
      { id: "belotti", label: "Belotti" },
      { id: "betlift", label: "Betlift" },
      { id: "biglion", label: "Biglion" },
      { id: "bobcat", label: "Bobcat" },
      { id: "boss", label: "Boss" },
      { id: "bt", label: "BT" },
      { id: "cascade", label: "Cascade" },
      { id: "case", label: "Case" },
      { id: "caterpillar", label: "Caterpillar" },
      { id: "cesab", label: "Cesab" },
      { id: "ceylift", label: "Ceylift" },
      { id: "cherry", label: "Cherry" },
      { id: "chl", label: "CHL" },
      { id: "clark", label: "Clark" },
      { id: "cleanvac", label: "Cleanvac" },
      { id: "clift", label: "Clift" },
      { id: "climax", label: "Climax" },
      { id: "combilift", label: "Combilift" },
      { id: "crown", label: "Crown" },
      { id: "ctc", label: "CTC" },
      { id: "ctPower", label: "CT-POWER" },
      { id: "cukurovaMachinery", label: "Cukurova Machinery" },
      { id: "dacha", label: "Dacha" },
      { id: "daewoo", label: "Daewoo" },
      { id: "dalian", label: "Dalian" },
      { id: "demo", label: "Demo" },
      { id: "outrun", label: "Outrun" },
      { id: "dieci", label: "Dieci" },
      { id: "dimex", label: "Dimex" },
      { id: "dlzLift", label: "DLZ Lift" },
      { id: "dolphin", label: "Dolphin" },
      { id: "doosan", label: "Doosan" },
      { id: "dragon", label: "Dragon" },
      { id: "energy", label: "Energy" },
      { id: "energyLift", label: "Energy Lift" },
      { id: "ep", label: "EP" },
      { id: "eurostar", label: "Eurostar" },
      { id: "everun", label: "Everun" },
      { id: "evoForklift", label: "Evo Forklift" },
      { id: "youAreAMouse", label: "You are a mouse" },
      { id: "federalPower", label: "Federal Power" },
      { id: "feeler", label: "Feeler" },
      { id: "fenwick", label: "Fenwick" },
      { id: "fiat", label: "Fiat" },
      { id: "fimax", label: "Fimax" },
      { id: "fmc", label: "FMC" },
      { id: "ftmhFantuzzi", label: "FTMH Fantuzzi" },
      { id: "fuda", label: "Fuda" },
      { id: "gcPower", label: "GC Power" },
      { id: "gmk", label: "GMK" },
      { id: "goodsense", label: "Goodsense" },
      { id: "gobblers", label: "Gobblers" },
      { id: "gp", label: "GP" },
      { id: "growa", label: "Growa" },
      { id: "gtPower", label: "GT POWER" },
      { id: "halla", label: "Halla" },
      { id: "weightlifting", label: "Weightlifting" },
      { id: "hangcha", label: "Hangcha" },
      { id: "hc", label: "HC" },
      { id: "hd", label: "HD" },
      { id: "hecha", label: "Hecha" },
      { id: "heden", label: "Heden" },
      { id: "held", label: "Held" },
      { id: "heli", label: "Heli" },
      { id: "hengwang", label: "hengwang" },
      { id: "henley", label: "Henley" },
      { id: "hercu", label: "Hercu" },
      { id: "hiab", label: "Hiab" },
      { id: "hibold", label: "Hibold" },
      { id: "hinowa", label: "Hinowa" },
      { id: "hoistLiftTruck", label: "Hoist Lift Truck" },
      { id: "hpsystems", label: "Hpsystems" },
      { id: "huaheh", label: "Huaheh" },
      { id: "huaya", label: "huaya" },
      { id: "hubtex", label: "Hubtex" },
      { id: "huLift", label: "Hu-Lift" },
      { id: "hyster", label: "Hyster" },
      { id: "hytsu", label: "Hytsu" },
      { id: "hyundai", label: "Hyundai" },
      { id: "icon", label: "Icon" },
      { id: "index", label: "Index" },
      { id: "iron", label: "Iron" },
      { id: "iLift", label: "I-LIFT" },
      { id: "imow", label: "Imow" },
      { id: "ismak", label: "Ismak" },
      { id: "jac", label: "JAC" },
      { id: "jcb", label: "JCB" },
      { id: "jetlift", label: "Jetlift" },
      { id: "johnMorgan", label: "John Morgan" },
      { id: "jungheinrich", label: "Jungheinrich" },
      { id: "kaizen", label: "Kaizen" },
      { id: "kalmar", label: "Kalmar" },
      { id: "floor", label: "FLOOR" },
      { id: "katana", label: "Katana" },
      { id: "kaup", label: "Kaup" },
      { id: "keskinova", label: "Keskinova" },
      { id: "kfm", label: "KFM" },
      { id: "kinglifter", label: "Kinglifter" },
      { id: "kion", label: "Kion" },
      { id: "komatsu", label: "Komatsu" },
      { id: "kubota", label: "Kubota" },
      { id: "kuntel", label: "Kuntel" },
      { id: "kuzeymak", label: "Kuzeymak" },
      { id: "lifton", label: "Lifton" },
      { id: "linda", label: "Linda" },
      { id: "linde", label: "Linde" },
      { id: "lion", label: "Lion" },
      { id: "loadLifter", label: "Load Lifter" },
      { id: "loc", label: "LOC" },
      { id: "lokomo", label: "Lokomo" },
      { id: "lonking", label: "Lonking" },
      { id: "ls", label: "LS" },
      { id: "magni", label: "Magni" },
      { id: "manitou", label: "Manitou" },
      { id: "maximal", label: "Maximal" },
      { id: "mercedesBenz", label: "Mercedes Benz" },
      { id: "mhyundai", label: "Mhyundai" },
      { id: "mitsubishi", label: "Mitsubishi" },
      { id: "mtc", label: "MTC" },
      { id: "multicar", label: "Multicar" },
      { id: "nissan", label: "Nissan" },
      { id: "nobleLift", label: "Noblelift" },
      { id: "om", label: "OM" },
      { id: "opta", label: "Opta" },
      { id: "optimum", label: "Optimum" },
      { id: "other", label: "Other" },
      { id: "ozmen", label: "Ozmen" },
      { id: "ozmenLift", label: "Ozmen Lift" },
      { id: "pakPisan", label: "Pak Pisan" },
      { id: "perkins", label: "Perkins" },
      { id: "power", label: "Power" },
      { id: "prestij", label: "Prestij" },
      { id: "pramac", label: "Pramac" },
      { id: "racine", label: "Racine" },
      { id: "still", label: "Still" },
      { id: "tcm", label: "TCM" },
      { id: "toyota", label: "Toyota" },
      { id: "yale", label: "Yale" },
    ],
    forRent: [
      { id: "alpha", label: "Alpha" },
      { id: "anadolulift", label: "Anadolulift" },
      { id: "asimato", label: "Asimato" },
      { id: "baoli", label: "baoli" },
      { id: "biglion", label: "Biglion" },
      { id: "caterpillar", label: "Caterpillar" },
      { id: "casab", label: "Casab" },
      { id: "ceylift", label: "Ceylift" },
      { id: "chl", label: "CHL" },
      { id: "clark", label: "Clark" },
      { id: "cukurova-machinery", label: "Cukurova Machinery" },
      { id: "daewoo", label: "Daewoo" },
      { id: "dalian", label: "Dalian" },
      { id: "dlz-lift", label: "DLZ Lift" },
      { id: "dolphin", label: "Dolphin" },
      { id: "doosan", label: "Doosan" },
      { id: "ep", label: "EP" },
      { id: "eurostar", label: "Eurostar" },
      { id: "evo-forklift", label: "Evo Forklift" },
      { id: "weightlifting", label: "Weightlifting" },
      { id: "hangcha", label: "Hangcha" },
      { id: "hc", label: "HC" },
      { id: "hecha", label: "Hecha" },
      { id: "held", label: "Held" },
      { id: "heli", label: "Heli" },
      { id: "hoist-lift-truck", label: "Hoist Lift Truck" },
      { id: "hpsystems", label: "Hpsystems" },
      { id: "huaheh", label: "Huaheh" },
      { id: "hyster", label: "Hyster" },
      { id: "hytsu", label: "Hytsu" },
      { id: "hyundai", label: "Hyundai" },
      { id: "jac", label: "JAC" },
      { id: "jcb", label: "JCB" },
      { id: "jetlift", label: "Jetlift" },
      { id: "floor", label: "FLOOR" },
      { id: "komatsu", label: "Komatsu" },
      { id: "linde", label: "Linde" },
      { id: "lonking", label: "Lonking" },
      { id: "lts", label: "LTS" },
      { id: "manforce", label: "Manforce" },
      { id: "manitou", label: "Manitou" },
      { id: "million", label: "Million" },
      { id: "mitsubishi", label: "Mitsubishi" },
      { id: "mmg", label: "MMG" },
      { id: "moffett", label: "Moffett" },
      { id: "mst", label: "MST" },
      { id: "nbo", label: "NBO" },
      { id: "on-the-net", label: "On the net" },
      { id: "neumann", label: "Neumann" },
      { id: "newlift", label: "Newlift" },
      { id: "okta-lift", label: "Okta Lift" },
      { id: "ols-lift", label: "OLS Lift" },
      { id: "reach-truck", label: "Reach Truck" },
      { id: "rkn", label: "RKN" },
      { id: "runtx", label: "Runtx" },
      { id: "ry", label: "R.Y." },
      { id: "to-you-too", label: "To you too" },
      { id: "sanica", label: "Sanica" },
      { id: "seikatsu", label: "seikatsu" },
      { id: "seonlift", label: "Seonlift" },
      { id: "sinomach", label: "Sinomach" },
      { id: "smv", label: "SMV" },
      { id: "dont-say-anything", label: "Don't say anything" },
      { id: "steiner", label: "Steiner" },
      { id: "stier", label: "Stier" },
      { id: "still", label: "Still" },
      { id: "taillift", label: "Taillift" },
      { id: "tavol", label: "Tavol" },
      { id: "tcm", label: "TCM" },
      { id: "teu", label: "Teu" },
      { id: "toplift", label: "Toplift" },
      { id: "toyota", label: "Toyota" },
      { id: "tysim", label: "Tysim" },
      { id: "reputation", label: "REPUTATION" },
      { id: "uvc", label: "UVC" },
      { id: "wecan", label: "Wecan" },
      { id: "xilin", label: "Xilin" },
      { id: "yale", label: "Yale" },
      { id: "lew", label: "Lew" },
      { id: "ygs", label: "YGS" },
      { id: "youtob", label: "Youtob" },
      { id: "zass", label: "Zass" },
      { id: "other", label: "Other" },
    ],
    partsAttachments: [
      { id: "forSale", label: "For sale" },
      { id: "forRent", label: "For rent" },
      { id: "partsAttachments", label: "Parts & Attachments" },
    ],
  },
};
