// 📁 src/config/categories/construction.js
export const constructionConfig = {
  title: "Construction Machinery & Industry",
  level1: [
    { id: "constructionMachinery", label: "Construction Machinery" },
    { id: "agriculturalMachinery", label: "Agricultural Machinery" },
    { id: "industry", label: "Industry" },
    { id: "electricityEnergy", label: "Electricity & Energy" },
  ],
  level2: {
    constructionMachinery: [
      { id: "forSale", label: "For sale" },
      { id: "forRent", label: "For rent" },
      { id: "partsAttachments", label: "Parts & Attachments" },
    ],
    agriculturalMachinery: [
      { id: "tractors", label: "Tractor" },
      { id: "soilCultivation", label: "Soil Cultivation" },
      { id: "harvestThresh", label: "Harvest & Thresh" },
      { id: "plantCare", label: "Plant Care" },
      { id: "plantingSowing", label: "Planting & Sowing" },
      { id: "fertilization", label: "Fertilization" },
      { id: "irrigation", label: "Irrigation" },
      { id: "livestockFarming", label: "Livestock farming" },
      { id: "transport", label: "Transport" },
      { id: "attachmentsSpareParts", label: "Attachments & Spare Parts" },
    ],
    industry: [
      { id: "industrialMachinery", label: "Industrial Machinery" },
      { id: "industrialKitchen", label: "Industrial Kitchen" },
      { id: "industrialFurniture", label: "Industrial Furniture" },
      { id: "industrialCleaning", label: "Industrial Cleaning" },
      { id: "industrialHardware", label: "Industrial Hardware" },
      { id: "transportStacking", label: "Transport & Stacking" },
      { id: "compressor", label: "Compressor" },
      { id: "shelvingProductDisplay", label: "Shelving & Product Display" },
      { id: "tentAwningShutter", label: "Tent, Awning & Shutter" },
      { id: "containerCabin", label: "Container & Cabin" },
      {
        id: "protectionShelterSystems",
        label: "Protection and Shelter Syste...",
      },
    ],
    electricityEnergy: [
      { id: "generator", label: "Generator" },
      { id: "electricElectronics", label: "Electric & Electronics" },
      { id: "fuelProducts", label: "Fuel Products" },
      { id: "pressureVessels", label: "Pressure Vessels" },
      { id: "solarPanel", label: "Solar panel" },
      { id: "windTurbine", label: "Wind Turbine" },
      { id: "waterTurbine", label: "Water Turbine" },
    ],
  },
  level3: {
    forSale: [
      { id: "asphaltMachine", label: "Asphalt Machine" },
      { id: "backhoeLoader", label: "Backhoe Loader (Excavator-..." },
      { id: "articulatedDumper", label: "Articulated Dumper" },
      { id: "concreteDistributor", label: "Concrete Distributor" },
      { id: "concretePump", label: "Concrete Pump" },
      { id: "garbageCompactor", label: "Garbage Compactor" },
      { id: "railwayMachine", label: "Railway Machine" },
      { id: "dieselHammer", label: "Diesel Hammer" },
      { id: "dozer", label: "Dozer" },
      { id: "excavatorBucket", label: "Excavator (Bucket)" },
      { id: "finisher", label: "Finisher" },
      { id: "boredPileMachine", label: "Bored Pile Machine" },
      { id: "grader", label: "Grader" },
      { id: "canalTrenchDigger", label: "Canal & Trench Digger" },
      { id: "snowmobile", label: "Snowmobile" },
      { id: "snowPlowTruck", label: "Snow Plow Truck" },
      { id: "snowBlower", label: "Snow Blower" },
      { id: "rockDrillAnchor", label: "Rock Drill (Anchor)" },
      { id: "rockTruck", label: "Rock Truck" },
      { id: "crushingScreeningPlant", label: "Crushing Screening Plant" },
      { id: "towerCrane", label: "Tower Crane" },
      { id: "loader", label: "Loader" },
      { id: "mobileElevator", label: "Mobile Elevator" },
      { id: "mobileCrusher", label: "Mobile Crusher" },
      { id: "mobileCrane", label: "Mobile Crane" },
      { id: "cylinder", label: "Cylinder" },
      { id: "drillingMachine", label: "Drilling Machine" },
      { id: "telescopicLoader", label: "Telescopic Loader" },
      { id: "transmixer", label: "Transmixer" },
    ],
    forRent: [
      { id: "asphaltMachine", label: "Asphalt Machine" },
      {
        id: "backhoeLoaderDiggerLoader",
        label: "Backhoe Loader (Digger & L...",
      },
      { id: "concreteDistributor", label: "Concrete Distributor" },
      { id: "concretePump", label: "Concrete Pump" },
      { id: "garbageCompactor", label: "Garbage Compactor" },
      { id: "dieselHammer", label: "Diesel Hammer" },
      { id: "dozer", label: "Dozer" },
      { id: "excavatorBucket", label: "Excavator (Bucket)" },
      { id: "finisher", label: "Finisher" },
      { id: "boredPileMachine", label: "Bored Pile Machine" },
      { id: "grader", label: "Grader" },
      { id: "canalTrenchDigger", label: "Canal & Trench Digger" },
      { id: "snowPlowTruck", label: "Snow Plow Truck" },
      { id: "rockDrill", label: "Rock Drill" },
      { id: "rockTruck", label: "Rock Truck" },
      { id: "crushingScreeningPlant", label: "Crushing Screening Plant" },
      { id: "towerCrane", label: "Tower Crane" },
      { id: "loader", label: "Loader" },
      { id: "mobileElevator", label: "Mobile Elevator" },
      { id: "mobileCrusher", label: "Mobile Crusher" },
      { id: "mobileCrane", label: "Mobile Crane" },
      { id: "cylinder", label: "Cylinder" },
      { id: "drillingMachine", label: "Drilling Machine" },
      { id: "telescopicLoader", label: "Telescopic Loader" },
      { id: "transmixer", label: "Transmixer" },
    ],
    partsAttachments: [
      { id: "asphaltMachineParts", label: "Asphalt Machine Parts" },
      { id: "backhoeLoaderParts", label: "Backhoe Loader Parts" },
      { id: "concretePumpParts", label: "Concrete Pump Parts" },
      { id: "railwayMachineParts", label: "Railway Machine Parts" },
      { id: "dozerParts", label: "Dozer Parts" },
      { id: "excavatorParts", label: "Excavator Parts" },
      { id: "paverParts", label: "Paver Parts" },
      { id: "forkliftParts", label: "Forklift Parts" },
      { id: "graderParts", label: "Grader Parts" },
      { id: "rockDrillParts", label: "Rock Drill Parts" },
      { id: "rockTruckSpareParts", label: "Rock Truck Spare Parts" },
      { id: "crusherParts", label: "Crusher Parts" },
      { id: "towerCraneParts", label: "Tower Crane Parts" },
      { id: "loaderParts", label: "Loader Parts" },
      { id: "mobileElevatorParts", label: "Mobile Elevator Parts" },
      { id: "mobileCrusherParts", label: "Mobile Crusher Parts" },
      { id: "mobileCraneParts", label: "Mobile Crane Parts" },
      { id: "cylinderParts", label: "Cylinder Parts" },
      { id: "drillingMachineParts", label: "Drilling Machine Parts" },
      { id: "telescopicLoaderParts", label: "Telescopic Loader Parts" },
      { id: "truckMixerParts", label: "Truck Mixer Parts" },
    ],
    tractors: [
      { id: "agrifarm", label: "Agrifarm" },
      { id: "agripower", label: "Agripower" },
      { id: "agromet", label: "Agromet" },
      { id: "agt", label: "AGT" },
      { id: "antonioCarraro", label: "Antonio Carraro" },
      { id: "arbos", label: "Arbos" },
      { id: "artrakSuperline", label: "Artrak Superline" },
      { id: "lion", label: "Lion" },
      { id: "virgo", label: "Virgo" },
      { id: "capitalCity", label: "Capital city" },
      { id: "bcs", label: "BCS" },
      { id: "belarus", label: "Belarus" },
      { id: "bmc", label: "BMC" },
      { id: "bull", label: "Bull" },
      { id: "bolgar", label: "Bolgar" },
      { id: "bolinderMunktell", label: "Bolinder-Munktell" },
      { id: "boron", label: "Boron" },
      { id: "bozok", label: "Bozok" },
      { id: "branson", label: "Branson" },
      { id: "captain", label: "Captain" },
      { id: "carraro", label: "Carraro" },
      { id: "caseIh", label: "Case IH" },
      { id: "cherry", label: "Cherry" },
      { id: "claas", label: "Claas" },
      { id: "davidBrown", label: "David Brown" },
      { id: "deutzFahr", label: "Deutz Fahr" },
      { id: "dexta", label: "Dexta" },
      { id: "ebro", label: "Ebro" },
      { id: "eich", label: "Eich" },
      { id: "eltar", label: "Eltar" },
      { id: "erkunt", label: "Erkunt" },
      { id: "farmtrac", label: "Farmtrac" },
      { id: "conqueror", label: "Conqueror" },
      { id: "fendt", label: "Fendt" },
      { id: "ferrari", label: "Ferrari" },
      { id: "fiat", label: "Fiat" },
      { id: "ford", label: "Ford" },
      { id: "photon", label: "Photon" },
      { id: "goldoni", label: "Goldoni" },
      { id: "grace", label: "Grace" },
      { id: "gutbrod", label: "Gutbrod" },
      { id: "guldner", label: "Guldner" },
      { id: "hanomag", label: "Hanomag" },
      { id: "blend", label: "Blend" },
      { id: "harsh", label: "Harsh" },
      { id: "calligrapher", label: "Calligrapher" },
      { id: "hema", label: "Hema" },
      { id: "holder", label: "Holder" },
      { id: "husqvarna", label: "Husqvarna" },
      { id: "hurlimann", label: "Hurlimann" },
      { id: "imt", label: "IMT" },
      { id: "international", label: "International" },
      { id: "irtem", label: "Irtem" },
      { id: "isbora", label: "Isbora" },
      { id: "jcb", label: "JCB" },
      { id: "jinma", label: "Jinma" },
      { id: "johnDeere", label: "John Deere" },
      { id: "kaan", label: "Kaan" },
      { id: "blackstone", label: "Blackstone" },
      { id: "katsu", label: "Katsu" },
      { id: "kioti", label: "Kioti" },
      { id: "kubota", label: "Kubota" },
      { id: "lamborghini", label: "Lamborghini" },
      { id: "landini", label: "Landini" },
      { id: "leyland", label: "Leyland" },
      { id: "lg", label: "LG" },
      { id: "lombardin", label: "Lombardin" },
      { id: "lsTractor", label: "LS Tractor" },
      { id: "mahindra", label: "Mahindra" },
      { id: "man", label: "MAN" },
      { id: "masseyFerguson", label: "Massey Ferguson" },
      { id: "masseyHarris", label: "Massey Harris" },
      { id: "mastash", label: "Mastash" },
      { id: "mccormick", label: "McCormick" },
      { id: "mehmetSimseker", label: "Mehmet Simseker" },
      { id: "mercedesBenz", label: "Mercedes Benz" },
      { id: "newHolland", label: "New Holland" },
      { id: "nibbi", label: "Nibbi" },
      { id: "nuoman", label: "Nuoman" },
      { id: "beet", label: "Beet" },
      { id: "perkis", label: "Perkis" },
      { id: "porsche", label: "Porsche" },
      { id: "renault", label: "Renault" },
      { id: "same", label: "Same" },
      { id: "solise", label: "Solise" },
      { id: "steyr", label: "Steyr" },
      { id: "sunway", label: "Sunway" },
      { id: "superMajor", label: "Super Major" },
      { id: "superStar", label: "Super Star" },
      { id: "tafe", label: "Tafe" },
      { id: "taral", label: "Taral" },
      { id: "towgo", label: "Towgo" },
      { id: "tumosan", label: "Tumosan" },
      { id: "turkishTractor", label: "Turkish Tractor" },
      { id: "tym", label: "TYM" },
      { id: "universal", label: "Universal" },
      { id: "ural", label: "Ural" },
      { id: "ursus", label: "Ursus" },
      { id: "uzel", label: "Uzel" },
      { id: "valpadan", label: "Valpadan" },
      { id: "valtra", label: "Valtra" },
      { id: "volvo", label: "Volvo" },
      { id: "rain", label: "Rain" },
      { id: "yanmar", label: "Yanmar" },
      { id: "yto", label: "YTO" },
      { id: "zetor", label: "Zetor" },
    ],
    soilCultivation: [
      { id: "treeRemovalMachine", label: "Tree Removal Machine" },
      { id: "tillerMachine", label: "Tiller Machine" },
      { id: "chiselSubsoiler", label: "Chisel & Subsoiler" },
      { id: "discHarrow", label: "Disc harrow" },
      { id: "castingRoller", label: "Casting Roller" },
      { id: "cultivator", label: "Cultivator" },
      { id: "laserLevelingSmoothing", label: "Laser Leveling & Smoothing" },
      { id: "mulchMachine", label: "Mulch Machine" },
      { id: "woodCrusherMachine", label: "Wood Crusher Machine" },
      { id: "plow", label: "Plow" },
      { id: "rotovator", label: "Rotovator" },
      { id: "mulcherMachine", label: "Mulcher Machine" },
      { id: "backMakingMachine", label: "Back Making Machine" },
      { id: "stoneCrusherMachine", label: "Stone Crusher Machine" },
      { id: "stoneCollectingMachine", label: "Stone Collecting Machine" },
      { id: "harrow", label: "Harrow" },
      { id: "soilLawnAeration", label: "Soil & Lawn Aeration" },
      { id: "earthAugerMachine", label: "Earth Auger Machine" },
      { id: "soilGrindingMachine", label: "Soil Grinding Machine" },
    ],
    harvestThresh: [
      { id: "harvester", label: "Harvester" },
      { id: "treeShakingMachine", label: "Tree Shaking Machine" },
      { id: "sunflowerHarvestTray", label: "Sunflower Harvest Tray" },
      {
        id: "sunflowerHarvesterPicking",
        label: "Sunflower Harvester & Picki...",
      },
      { id: "balerMachine", label: "Baler Machine" },
      { id: "bicerbaglar", label: "Bicerbaglar" },
      { id: "gradingMachine", label: "Grading Machine" },
      { id: "cottonGinMachine", label: "Cotton Gin Machine" },
      { id: "tomatoHarvestingMachine", label: "Tomato Harvesting Machine" },
      {
        id: "hazelnutHarvesterCollecting",
        label: "Hazelnut Harvester & Collec...",
      },
      { id: "peanutHarvester", label: "Peanut Harvester" },
      { id: "threshingMachine", label: "Threshing Machine" },
      { id: "pumpkinHarvester", label: "Pumpkin Harvester" },
      { id: "dryer", label: "Dryer" },
      { id: "fruitOlivePicking", label: "Fruit & Olive Picking" },
      { id: "cornHarvestTray", label: "Corn Harvest Tray" },
      { id: "cottonPickingMachine", label: "Cotton Picking Machine" },
      { id: "sugarBeetHarvester", label: "Sugar Beet Harvester" },
      { id: "potatoOnionDigging", label: "Potato & Onion Digging" },
      { id: "riceHarvester", label: "Rice Harvester" },
      { id: "tasselCuttingMachine", label: "Tassel Cutting Machine" },
      { id: "hayMachine", label: "Hay Machine" },
      { id: "silageMachine", label: "Silage Machine" },
      { id: "silagePackingMachine", label: "Silage Packing Machine" },
      { id: "peelingMachine", label: "Peeling Machine" },
      { id: "seedScreeningMachine", label: "Seed Screening Machine" },
      { id: "oliveSievingMachine", label: "Olive Sieving Machine" },
    ],
    plantCare: [
      { id: "pruningMachine", label: "Pruning Machine" },
      { id: "meadowLawnGrassMowing", label: "Meadow, Lawn & Grass Mow..." },
      { id: "sickleScytheMachine", label: "Sickle & Scythe Machine" },
      { id: "pelletMachine", label: "Pellet Machine" },
      { id: "preparingSawdust", label: "Preparing Sawdust" },
      { id: "blowingCollectingMachine", label: "Blowing Collecting Machine" },
      {
        id: "leafBranchShredderMachine",
        label: "Leaf & Branch Shredder Mac...",
      },
    ],
    plantingSowing: [
      { id: "seedingMachine", label: "Seeding Machine" },
      { id: "grainPlantingDrill", label: "Grain Planting Drill" },
      { id: "potatoOnionBread", label: "Potato & Onion Bread" },
      { id: "tobaccoPlantingMachine", label: "Tobacco Planting Machine" },
    ],
    fertilization: [
      {
        id: "fertilizerSpreadingSpreader",
        label: "Fertilizer Spreading & Sprea...",
      },
      { id: "fertilizerMixer", label: "Fertilizer Mixer" },
      { id: "fertilizerDryer", label: "Fertilizer Dryer" },
      { id: "fertilizerCrushing", label: "Fertilizer Crushing" },
      { id: "fertilizerPump", label: "Fertilizer Pump" },
      { id: "manureSeparator", label: "Manure Separator" },
      { id: "manureScraper", label: "Manure Scraper" },
      { id: "compostMachine", label: "Compost Machine" },
    ],
    irrigation: [
      { id: "fertilizerTank", label: "Fertilizer Tank" },
      { id: "beetrootEngine", label: "Beetroot Engine" },
      { id: "irrigationMachine", label: "Irrigation Machine" },
      { id: "waterPumpMotor", label: "Water Pump & Motor" },
      { id: "waterTanker", label: "Water Tanker" },
    ],
    livestockFarming: [
      { id: "beekeepingSupplies", label: "Beekeeping Supplies" },
      { id: "petScratchingBrush", label: "Pet Scratching Brush" },
      {
        id: "animalSlaughterhouseEquipment",
        label: "Animal Slaughterhouse Equi...",
      },
      { id: "milkingMachine", label: "Milking Machine" },
      { id: "feedCrushingCrushing", label: "Feed Crushing & Crushing" },
      { id: "feedMixerMachine", label: "Feed Mixer Machine" },
      { id: "feedProductionMachine", label: "Feed Production Machine" },
      { id: "barnEquipment", label: "Barn Equipment" },
    ],
    transport: [
      { id: "trailer", label: "Trailer" },
      { id: "conveyorBeltScrew", label: "Conveyor, Belt & Screw" },
      { id: "logTractorCrane", label: "Log Tractor Crane" },
      { id: "cratesBaskets", label: "Crates & Baskets" },
    ],
    industrialMachinery: [
      { id: "woodFurniture", label: "Wood & Furniture" },
      { id: "packagingPacking", label: "Packaging & Packing" },
      { id: "glassPlasticChemicals", label: "Glass, Plastic & Chemicals" },
      { id: "food", label: "Food" },
      { id: "building", label: "Building" },
      { id: "printingAdvertising", label: "Printing & Advertising" },
      { id: "mining", label: "Mining" },
      { id: "metalworking", label: "Metalworking" },
      { id: "automotive", label: "Automotive" },
      { id: "textilesShoes", label: "Textiles & Shoes" },
      { id: "heatVentilation", label: "Heat & Ventilation" },
      { id: "sparePartsAccessories", label: "Spare Parts & Accessories" },
      { id: "bulkSales", label: "Bulk Sales" },
    ],
    industrialKitchen: [
      { id: "foodPreparation", label: "Food Preparation" },
      { id: "cookingEquipment", label: "Cooking Equipment" },
      { id: "foodCoolingStorage", label: "Food Cooling & Storage" },
      { id: "barCafeRestaurant", label: "Bar, Cafe & Restaurant" },
      { id: "patisserieBakery", label: "Patisserie & Bakery" },
      { id: "dishwasherCleaning", label: "Dishwasher & Cleaning" },
      { id: "sink", label: "Sink" },
      { id: "service", label: "Service" },
      { id: "mobileStalls", label: "Mobile Stalls" },
      { id: "bulkSales", label: "Bulk Sales" },
    ],
    industrialFurniture: [
      { id: "barNightclubFurniture", label: "Bar & Nightclub Furniture" },
      { id: "hospitalFurniture", label: "Hospital Furniture" },
      { id: "cafeRestaurantFurniture", label: "Cafe & Restaurant Furniture" },
      { id: "hotelFurniture", label: "Hotel Furniture" },
    ],
    industrialCleaning: [
      { id: "laundry", label: "Laundry" },
      { id: "disinfectionSystems", label: "Disinfection Systems" },
      { id: "carpetCleaning", label: "Carpet Cleaning" },
      { id: "washingSweeping", label: "Washing & Sweeping" },
      { id: "sparePartsAccessories", label: "Spare Parts & Accessories" },
      { id: "bulkSales", label: "Bulk Sales" },
    ],
    industrialHardware: [
      { id: "wood", label: "Wood" },
      { id: "building", label: "Building" },
      { id: "metal", label: "Metal" },
      { id: "jobSecurity", label: "Job security" },
      { id: "coolTools", label: "Cool Tools" },
      { id: "measuringInstruments", label: "Measuring Instruments" },
      { id: "microInstruments", label: "Micro Instruments" },
      { id: "smallHandTools", label: "Small Hand Tools" },
      { id: "pipeProcessingEquipment", label: "Pipe Processing Equipment" },
    ],
    transportStacking: [
      { id: "forklifts", label: "Forklifts" },
      { id: "terminalTractor", label: "Terminal Tractor" },
      { id: "liftingAttachments", label: "Lifting Attachments" },
      { id: "elevators", label: "Elevators" },
      {
        id: "scaffoldingFormworkSystems",
        label: "Scaffolding & Formwork Sys...",
      },
      { id: "scales", label: "Scales" },
      { id: "platforms", label: "Platforms" },
      { id: "palletTrucks", label: "Pallet trucks" },
      { id: "stackingMachines", label: "Stacking Machines" },
      { id: "escalator", label: "Escalator" },
      { id: "cratesBaskets", label: "Crates & Baskets" },
      { id: "cargoTransportCarts", label: "Cargo Transport Carts" },
    ],
    compressor: [
      { id: "reciprocating", label: "Reciprocating" },
      { id: "screwed", label: "Screwed" },
      { id: "lean", label: "Lean" },
      { id: "dryersFilters", label: "Dryers & Filters" },
      { id: "sparePartsAccessories", label: "Spare Parts & Accessories" },
    ],
    shelvingProductDisplay: [
      { id: "marketEquipment", label: "Market Equipment" },
      { id: "shelvesAisles", label: "Shelves and Aisles" },
      { id: "stands", label: "Stands" },
      {
        id: "showcasesCountersCabinets",
        label: "Showcases, Counters & Cab...",
      },
      { id: "showcaseMannequins", label: "Showcase Mannequins" },
      { id: "accessories", label: "Accessories" },
      { id: "bulkSales", label: "Bulk Sales" },
    ],
    tentAwningShutter: [
      { id: "industrialTents", label: "Industrial Tents" },
      { id: "awningTarpaulin", label: "Awning & Tarpaulin" },
      { id: "shuttersBlinds", label: "Shutters & Blinds" },
      { id: "photocellAutomaticDoor", label: "Photocell & Automatic Door" },
      { id: "fastPvcDoor", label: "Fast PVC Door" },
    ],
    containerCabin: [
      { id: "cabins", label: "Cabins" },
      { id: "containers", label: "Containers" },
    ],
    protectionShelterSystems: [
      { id: "earthquakePanicCabins", label: "Earthquake & Panic Cabins" },
      { id: "cbrnShelters", label: "CBRN Shelters" },
      { id: "mineRefugeChambers", label: "Mine Refuge Chambers" },
    ],
    generator: [
      { id: "gasoline", label: "Gasoline" },
      { id: "diesel", label: "Diesel" },
      { id: "lpgNaturalGas", label: "LPG & Natural Gas" },
      { id: "sparePartsAccessories", label: "Spare Parts & Accessories" },
    ],
    electricityEnergy: [
      { id: "alternator", label: "Alternator" },
      { id: "distributionTransformer", label: "Distribution Transformer" },
      { id: "electricMotors", label: "Electric Motors" },
      { id: "industrialElectronics", label: "Industrial Electronics" },
      { id: "inverter", label: "Inverter" },
      { id: "isolationTransformer", label: "Isolation Transformer" },
      { id: "compensationBoard", label: "Compensation Board" },
      { id: "reactors", label: "Reactors" },
      { id: "rectifiers", label: "Rectifiers" },
      { id: "switchgearMaterials", label: "Switchgear Materials" },
      { id: "chargeRegulator", label: "Charge Regulator" },
      { id: "voltageRegulator", label: "Voltage Regulator" },
    ],
    fuelProducts: [
      { id: "fuelPump", label: "Fuel Pump" },
      { id: "fuelTank", label: "Fuel Tank" },
      { id: "fillingGun", label: "Filling Gun" },
      { id: "lpgPump", label: "LPG Pump" },
      { id: "lpgTank", label: "LPG Tank" },
      { id: "counter", label: "Counter" },
    ],
  },
  level4: {
    forklifts: [
      { id: "forSale", label: "For sale" },
      { id: "forRent", label: "For rent" },
      { id: "partsAttachments", label: "Parts & Attachments" },
    ],
  },
  level5: {
    forSale: [
      { id: "ahilift", label: "Ahilift" },
      { id: "alpha", label: "Alpha" },
      { id: "alimar", label: "Alimar" },
      { id: "allisChalmers", label: "Allis Chalmers" },
      { id: "anadolulift", label: "Anadolulift" },
      { id: "aPower", label: "A-Power" },
      { id: "arlift", label: "Arlift" },
      { id: "armani", label: "Armani" },
      { id: "asimato", label: "Asimato" },
      { id: "atf", label: "ATF" },
      { id: "atlas", label: "Atlas" },
      { id: "athleteTrucks", label: "Athlete Trucks" },
      { id: "attack", label: "Attack" },
      { id: "ausa", label: "Ausa" },
      { id: "bagsan", label: "Bagsan" },
      { id: "balkancar", label: "Balkancar" },
      { id: "baoli", label: "baoli" },
      { id: "baumann", label: "Baumann" },
      { id: "belotti", label: "Belotti" },
      { id: "betlift", label: "Betlift" },
      { id: "biglion", label: "Biglion" },
      { id: "bobcat", label: "Bobcat" },
      { id: "boss", label: "Boss" },
      { id: "bt", label: "BT" },
      { id: "cascade", label: "Cascade" },
      { id: "case", label: "Case" },
      { id: "caterpillar", label: "Caterpillar" },
      { id: "cesab", label: "Cesab" },
      { id: "ceylift", label: "Ceylift" },
      { id: "cherry", label: "Cherry" },
      { id: "chl", label: "CHL" },
      { id: "clark", label: "Clark" },
      { id: "cleanvac", label: "Cleanvac" },
      { id: "clift", label: "Clift" },
      { id: "climax", label: "Climax" },
      { id: "combilift", label: "Combilift" },
      { id: "crown", label: "Crown" },
      { id: "ctc", label: "CTC" },
      { id: "ctPower", label: "CT-POWER" },
      { id: "cukurovaMachinery", label: "Cukurova Machinery" },
      { id: "dacha", label: "Dacha" },
      { id: "daewoo", label: "Daewoo" },
      { id: "dalian", label: "Dalian" },
      { id: "demo", label: "Demo" },
      { id: "outrun", label: "Outrun" },
      { id: "dieci", label: "Dieci" },
      { id: "dimex", label: "Dimex" },
      { id: "dlzLift", label: "DLZ Lift" },
      { id: "dolphin", label: "Dolphin" },
      { id: "doosan", label: "Doosan" },
      { id: "dragon", label: "Dragon" },
      { id: "energy", label: "Energy" },
      { id: "energyLift", label: "Energy Lift" },
      { id: "ep", label: "EP" },
      { id: "eurostar", label: "Eurostar" },
      { id: "everun", label: "Everun" },
      { id: "evoForklift", label: "Evo Forklift" },
      { id: "youAreAMouse", label: "You are a mouse" },
      { id: "federalPower", label: "Federal Power" },
      { id: "feeler", label: "Feeler" },
      { id: "fenwick", label: "Fenwick" },
      { id: "fiat", label: "Fiat" },
      { id: "fimax", label: "Fimax" },
      { id: "fmc", label: "FMC" },
      { id: "ftmhFantuzzi", label: "FTMH Fantuzzi" },
      { id: "fuda", label: "Fuda" },
      { id: "gcPower", label: "GC Power" },
      { id: "gmk", label: "GMK" },
      { id: "goodsense", label: "Goodsense" },
      { id: "gobblers", label: "Gobblers" },
      { id: "gp", label: "GP" },
      { id: "growa", label: "Growa" },
      { id: "gtPower", label: "GT POWER" },
      { id: "halla", label: "Halla" },
      { id: "weightlifting", label: "Weightlifting" },
      { id: "hangcha", label: "Hangcha" },
      { id: "hc", label: "HC" },
      { id: "hd", label: "HD" },
      { id: "hecha", label: "Hecha" },
      { id: "heden", label: "Heden" },
      { id: "held", label: "Held" },
      { id: "heli", label: "Heli" },
      { id: "hengwang", label: "hengwang" },
      { id: "henley", label: "Henley" },
      { id: "hercu", label: "Hercu" },
      { id: "hiab", label: "Hiab" },
      { id: "hibold", label: "Hibold" },
      { id: "hinowa", label: "Hinowa" },
      { id: "hoistLiftTruck", label: "Hoist Lift Truck" },
      { id: "hpsystems", label: "Hpsystems" },
      { id: "huaheh", label: "Huaheh" },
      { id: "huaya", label: "huaya" },
      { id: "hubtex", label: "Hubtex" },
      { id: "huLift", label: "Hu-Lift" },
      { id: "hyster", label: "Hyster" },
      { id: "hytsu", label: "Hytsu" },
      { id: "hyundai", label: "Hyundai" },
      { id: "icon", label: "Icon" },
      { id: "index", label: "Index" },
      { id: "iron", label: "Iron" },
      { id: "iLift", label: "I-LIFT" },
      { id: "imow", label: "Imow" },
      { id: "ismak", label: "Ismak" },
      { id: "jac", label: "JAC" },
      { id: "jcb", label: "JCB" },
      { id: "jetlift", label: "Jetlift" },
      { id: "johnMorgan", label: "John Morgan" },
      { id: "jungheinrich", label: "Jungheinrich" },
      { id: "kaizen", label: "Kaizen" },
      { id: "kalmar", label: "Kalmar" },
      { id: "floor", label: "FLOOR" },
      { id: "katana", label: "Katana" },
      { id: "kaup", label: "Kaup" },
      { id: "keskinova", label: "Keskinova" },
      { id: "kfm", label: "KFM" },
      { id: "kinglifter", label: "Kinglifter" },
      { id: "kion", label: "Kion" },
      { id: "komatsu", label: "Komatsu" },
      { id: "kubota", label: "Kubota" },
      { id: "kuntel", label: "Kuntel" },
      { id: "kuzeymak", label: "Kuzeymak" },
      { id: "lifton", label: "Lifton" },
      { id: "linda", label: "Linda" },
      { id: "linde", label: "Linde" },
      { id: "lion", label: "Lion" },
      { id: "loadLifter", label: "Load Lifter" },
      { id: "loc", label: "LOC" },
      { id: "lokomo", label: "Lokomo" },
      { id: "lonking", label: "Lonking" },
      { id: "ls", label: "LS" },
      { id: "magni", label: "Magni" },
      { id: "manitou", label: "Manitou" },
      { id: "maximal", label: "Maximal" },
      { id: "mercedesBenz", label: "Mercedes Benz" },
      { id: "mhyundai", label: "Mhyundai" },
      { id: "mitsubishi", label: "Mitsubishi" },
      { id: "mtc", label: "MTC" },
      { id: "multicar", label: "Multicar" },
      { id: "nissan", label: "Nissan" },
      { id: "nobleLift", label: "Noblelift" },
      { id: "om", label: "OM" },
      { id: "opta", label: "Opta" },
      { id: "optimum", label: "Optimum" },
      { id: "other", label: "Other" },
      { id: "ozmen", label: "Ozmen" },
      { id: "ozmenLift", label: "Ozmen Lift" },
      { id: "pakPisan", label: "Pak Pisan" },
      { id: "perkins", label: "Perkins" },
      { id: "power", label: "Power" },
      { id: "prestij", label: "Prestij" },
      { id: "pramac", label: "Pramac" },
      { id: "racine", label: "Racine" },
      { id: "still", label: "Still" },
      { id: "tcm", label: "TCM" },
      { id: "toyota", label: "Toyota" },
      { id: "yale", label: "Yale" },
    ],
    forRent: [
      { id: "alpha", label: "Alpha" },
      { id: "anadolulift", label: "Anadolulift" },
      { id: "asimato", label: "Asimato" },
      { id: "baoli", label: "baoli" },
      { id: "biglion", label: "Biglion" },
      { id: "caterpillar", label: "Caterpillar" },
      { id: "casab", label: "Casab" },
      { id: "ceylift", label: "Ceylift" },
      { id: "chl", label: "CHL" },
      { id: "clark", label: "Clark" },
      { id: "cukurova-machinery", label: "Cukurova Machinery" },
      { id: "daewoo", label: "Daewoo" },
      { id: "dalian", label: "Dalian" },
      { id: "dlz-lift", label: "DLZ Lift" },
      { id: "dolphin", label: "Dolphin" },
      { id: "doosan", label: "Doosan" },
      { id: "ep", label: "EP" },
      { id: "eurostar", label: "Eurostar" },
      { id: "evo-forklift", label: "Evo Forklift" },
      { id: "weightlifting", label: "Weightlifting" },
      { id: "hangcha", label: "Hangcha" },
      { id: "hc", label: "HC" },
      { id: "hecha", label: "Hecha" },
      { id: "held", label: "Held" },
      { id: "heli", label: "Heli" },
      { id: "hoist-lift-truck", label: "Hoist Lift Truck" },
      { id: "hpsystems", label: "Hpsystems" },
      { id: "huaheh", label: "Huaheh" },
      { id: "hyster", label: "Hyster" },
      { id: "hytsu", label: "Hytsu" },
      { id: "hyundai", label: "Hyundai" },
      { id: "jac", label: "JAC" },
      { id: "jcb", label: "JCB" },
      { id: "jetlift", label: "Jetlift" },
      { id: "floor", label: "FLOOR" },
      { id: "komatsu", label: "Komatsu" },
      { id: "linde", label: "Linde" },
      { id: "lonking", label: "Lonking" },
      { id: "lts", label: "LTS" },
      { id: "manforce", label: "Manforce" },
      { id: "manitou", label: "Manitou" },
      { id: "million", label: "Million" },
      { id: "mitsubishi", label: "Mitsubishi" },
      { id: "mmg", label: "MMG" },
      { id: "moffett", label: "Moffett" },
      { id: "mst", label: "MST" },
      { id: "nbo", label: "NBO" },
      { id: "on-the-net", label: "On the net" },
      { id: "neumann", label: "Neumann" },
      { id: "newlift", label: "Newlift" },
      { id: "okta-lift", label: "Okta Lift" },
      { id: "ols-lift", label: "OLS Lift" },
      { id: "reach-truck", label: "Reach Truck" },
      { id: "rkn", label: "RKN" },
      { id: "runtx", label: "Runtx" },
      { id: "ry", label: "R.Y." },
      { id: "to-you-too", label: "To you too" },
      { id: "sanica", label: "Sanica" },
      { id: "seikatsu", label: "seikatsu" },
      { id: "seonlift", label: "Seonlift" },
      { id: "sinomach", label: "Sinomach" },
      { id: "smv", label: "SMV" },
      { id: "dont-say-anything", label: "Don't say anything" },
      { id: "steiner", label: "Steiner" },
      { id: "stier", label: "Stier" },
      { id: "still", label: "Still" },
      { id: "taillift", label: "Taillift" },
      { id: "tavol", label: "Tavol" },
      { id: "tcm", label: "TCM" },
      { id: "teu", label: "Teu" },
      { id: "toplift", label: "Toplift" },
      { id: "toyota", label: "Toyota" },
      { id: "tysim", label: "Tysim" },
      { id: "reputation", label: "REPUTATION" },
      { id: "uvc", label: "UVC" },
      { id: "wecan", label: "Wecan" },
      { id: "xilin", label: "Xilin" },
      { id: "yale", label: "Yale" },
      { id: "lew", label: "Lew" },
      { id: "ygs", label: "YGS" },
      { id: "youtob", label: "Youtob" },
      { id: "zass", label: "Zass" },
      { id: "other", label: "Other" },
    ],
    partsAttachments: [
      { id: "forSale", label: "For sale" },
      { id: "forRent", label: "For rent" },
      { id: "partsAttachments", label: "Parts & Attachments" },
    ],
  },
};
