// 📁 src/config/categories/realEstate.js
export const realEstateConfig = {
  title: "Real Estate",
  level1: [
    { id: "housing", label: "Housing" },
    { id: "workplace", label: "Workplace" },
    { id: "plot", label: "Plot" },
    { id: "housingProjects", label: "Housing Projects" },
    { id: "building", label: "Building" },
    { id: "timeshare", label: "Timeshare" },
    { id: "housingforsale", label: "Tourist Facility" },
  ],
  level2: {
    housing: [
      { id: "forSale", label: "For Sale" },
      { id: "forRent", label: "For Rent" },
      { id: "touristDailyRental", label: "Tourist Daily Rental" },
      { id: "housingForSale", label: "Housing For Sale" },
    ],
    workplace: [
      { id: "officeForSale", label: "For Sale" },
      { id: "officeForRent", label: "For Rent" },
      { id: "officeForsale", label: "For sale" },
      { id: "subletForRent", label: "Sublet For Rent" },
    ],
    plot: [
      { id: "floorPlot", label: "For Sale in Exchange for Floor Plot" },
      { id: "forsale", label: "For sale" },
      { id: "forrent", label: "For rent" },
    ],
    housingProjects: [
      { id: "newProjects", label: "New Projects" },
      { id: "underConstruction", label: "Under Construction" },
      { id: "readyToMove", label: "Ready to Move" },
    ],
    building: [
      { id: "BuildingForSale", label: "For Sale" },
      { id: "BuildingForRent", label: "For Rent" },
    ],
    timeshare: [
      { id: "timeshareSale", label: "For sale" },],
    housingforsale: [
      { id: "hotel", label: "For Sale" },
      { id: "resort", label: "For Rent" },
    ],
  },
  level3: {
    forSale: [
      { id: "apartment", label: "Apartment" },
      { id: "residence", label: "Residence" },
      { id: "familyHouse", label: "Family House" },
      { id: "villa", label: "Villa" },
      { id: "farmhouse", label: "Farmhouse" },
      { id: "mansion", label: "Mansion" },
      { id: "watersideApartment", label: "Waterside Apartment" },
      { id: "summery", label: "Summer House" },
    ],
    forRent: [
      { id: "apartment", label: "Apartment" },
      { id: "residence", label: "Residence" },
      { id: "familyHouse", label: "Family House" },
      { id: "villa", label: "Villa" },
      { id: "studio", label: "Studio" },
      { id: "sharedRoom", label: "Shared Room" },
    ],
    touristDailyRental: [
      { id: "apartment", label: "Apartment" },
      { id: "villa", label: "Villa" },
      { id: "summery", label: "Summer House" },
      { id: "cabin", label: "Cabin" },
    ],
    officeForRent: [
      { id: "fuelStation", label: "Fuel Station" },
      { id: "apartmentHouse", label: "Apartment House" },
      { id: "workshop", label: "Workshop" },
      { id: "shoppingMall", label: "Shopping Mall" },
      { id: "buffet", label: "Buffet" },
      { id: "bureauOffice", label: "Bureau & Office" },
      { id: "cafeBar", label: "Cafe & Bar" },
      { id: "farm", label: "Farm" },
      { id: "warehouseDepot", label: "Warehouse & Depot" },
      { id: "weddingHall", label: "Wedding Hall" },
      { id: "shopStore", label: "Shop & Store" },
      { id: "pharmacyMedical", label: "Pharmacy & Medical" },
      {
        id: "factoryProductionFacility",
        label: "Factory & Production Facility",
      },
      { id: "photoStudio", label: "Photo Studio" },
      { id: "garageParkingLot", label: "Garage & Parking Lot" },
      { id: "readyVirtualOffice", label: "Ready & Virtual Office" },
      {
        id: "businessCenterFloorOffice",
        label: "Business Center Floor & Office",
      },
      { id: "canteen", label: "Canteen" },
      { id: "countryBreakfastGarden", label: "Country & Breakfast Garden" },
      { id: "coffeehouse", label: "Coffeehouse" },
      { id: "completeBuilding", label: "Complete Building" },
      {
        id: "hairdresserBeautyCenter",
        label: "Hairdresser & Beauty Center",
      },
      { id: "mineQuarry", label: "Mine Quarry" },
      { id: "market", label: "Market" },
      { id: "surgery", label: "Surgery" },
      { id: "schoolCourse", label: "School & Course" },
      { id: "parking", label: "Parking" },
      { id: "carWashHairdresser", label: "Car Wash & Hairdresser" },
      {
        id: "patisserieBakeryDessert",
        label: "Patisserie & Bakery & Dessert",
      },
      { id: "marketplace", label: "Market place" },
      { id: "plaza", label: "Plaza" },
      { id: "plazaFloorOffice", label: "Plaza Floor & Office" },
      {
        id: "rehearsalRecordingStudio",
        label: "Rehearsal & Recording Studio",
      },
      { id: "radioStationTvChannel", label: "Radio Station & TV Channel" },
      { id: "restaurantDiner", label: "Restaurant & Diner" },
      { id: "residenceFloorOffice", label: "Residence Floor & Office" },
      { id: "healthCenter", label: "Health Center" },
      { id: "cinemaConferenceHall", label: "Cinema & Conference Hall" },
      { id: "spaTurkishBathSauna", label: "Spa, Turkish Bath & Sauna" },
      { id: "sportsFacility", label: "Sports Facility" },
      { id: "taxiStand", label: "Taxi Stand" },
      { id: "garage", label: "Garage" },
      { id: "villa", label: "Villa" },
      { id: "country", label: "Country" },
    ],
    officeForSale: [
      { id: "fuelStation", label: "Fuel Station" },
      { id: "apartmentHouse", label: "Apartment House" },
      { id: "workshop", label: "Workshop" },
      { id: "shoppingMall", label: "Shopping Mall" },
      { id: "buffet", label: "Buffet" },
      { id: "bureauOffice", label: "Bureau & Office" },
      { id: "cafeBar", label: "Cafe & Bar" },
      { id: "farm", label: "Farm" },
      { id: "warehouseDepot", label: "Warehouse & Depot" },
      { id: "weddingHall", label: "Wedding Hall" },
      { id: "shopStore", label: "Shop & Store" },
      { id: "pharmacyMedical", label: "Pharmacy & Medical" },
      {
        id: "factoryProductionFacility",
        label: "Factory & Production Facility",
      },
      { id: "photoStudio", label: "Photo Studio" },
      { id: "garageParkingLot", label: "Garage & Parking Lot" },
      { id: "readyVirtualOffice", label: "Ready & Virtual Office" },
      {
        id: "businessCenterFloorOffice",
        label: "Business Center Floor & Office",
      },
      { id: "canteen", label: "Canteen" },
      { id: "countryBreakfastGarden", label: "Country & Breakfast Garden" },
      { id: "coffeehouse", label: "Coffeehouse" },
      { id: "completeBuilding", label: "Complete Building" },
      {
        id: "hairdresserBeautyCenter",
        label: "Hairdresser & Beauty Center",
      },
      { id: "mineQuarry", label: "Mine Quarry" },
      { id: "market", label: "Market" },
      { id: "surgery", label: "Surgery" },
      { id: "schoolCourse", label: "School & Course" },
      { id: "parking", label: "Parking" },
      { id: "carWashHairdresser", label: "Car Wash & Hairdresser" },
      {
        id: "patisserieBakeryDessert",
        label: "Patisserie & Bakery & Dessert",
      },
      { id: "marketplace", label: "Market place" },
      { id: "plaza", label: "Plaza" },
      { id: "plazaFloorOffice", label: "Plaza Floor & Office" },
      {
        id: "rehearsalRecordingStudio",
        label: "Rehearsal & Recording Studio",
      },
      { id: "radioStationTvChannel", label: "Radio Station & TV Channel" },
      { id: "restaurantDiner", label: "Restaurant & Diner" },
      { id: "residenceFloorOffice", label: "Residence Floor & Office" },
      { id: "healthCenter", label: "Health Center" },
      { id: "cinemaConferenceHall", label: "Cinema & Conference Hall" },
      { id: "spaTurkishBathSauna", label: "Spa, Turkish Bath & Sauna" },
      { id: "sportsFacility", label: "Sports Facility" },
      { id: "taxiStand", label: "Taxi Stand" },
      { id: "garage", label: "Garage" },
      { id: "villa", label: "Villa" },
      { id: "country", label: "Country" },
    ],
    officeForsale: [
      { id: "privateOffice", label: "Private Office" },
      { id: "agency", label: "Agency" },
      { id: "fuelStation", label: "Fuel Station" },
      { id: "herbSpiceShop", label: "Herb & Spice Shop" },
      { id: "kindergartenNursery", label: "Kindergarten & Nursery" },
      { id: "apartmentHouse", label: "Apartment House" },
      { id: "vehicleShowroomService", label: "Vehicle Showroom & Service" },
      { id: "workshop", label: "Workshop" },
      { id: "shoppingMallStand", label: "Shopping Mall Stand" },
      { id: "fisherman", label: "Fisherman" },
      { id: "bar", label: "Bar" },
      { id: "bijouterie", label: "Bijouterie" },
      { id: "tuckshop", label: "Tuckshop" },
      { id: "buffet", label: "Buffet" },
      { id: "bureauOffice", label: "Bureau & Office" },
      { id: "cafe", label: "Cafe" },
      { id: "cdDvdStore", label: "CD & DVD Store" },
      { id: "mobilePhoneShop", label: "Mobile Phone Shop" },
      { id: "laundry", label: "Laundry" },
      { id: "teaHouse", label: "Tea House" },
      { id: "floristNursery", label: "Florist & Nursery" },
      { id: "farm", label: "Farm" },
      { id: "warehouseDepot", label: "Warehouse & Depot" },
      { id: "weddingHall", label: "Wedding Hall" },
      { id: "shopStore", label: "Shop & Store" },
      { id: "pharmacyMedical", label: "Pharmacy & Medical" },
      {
        id: "electricianHardwareStore",
        label: "Electrician & Hardware Store",
      },
      { id: "electronicsStore", label: "Electronics Store" },
      {
        id: "factoryProductionFacility",
        label: "Factory & Production Facility",
      },
      { id: "billingCenter", label: "Billing Center" },
      { id: "photoStudio", label: "Photo Studio" },
      { id: "nightClubDisco", label: "Night Club & Disco" },
      { id: "clothingStore", label: "Clothing Store" },
      { id: "optician", label: "Optician" },
      { id: "carpetWashing", label: "Carpet Washing" },
      { id: "nursingHome", label: "Nursing Home" },
      { id: "workshop2", label: "Workshop" },
      { id: "internetGameCafe", label: "Internet & Game Cafe" },
      { id: "businessCenter", label: "Business Center" },
      {
        id: "businessCenterFloorOffice",
        label: "Business Center Floor & Office",
      },
      { id: "butcher", label: "Butcher" },
      { id: "countryBreakfastGarden", label: "Country & Breakfast Garden" },
      { id: "coffeehouse", label: "Coffeehouse" },
      { id: "stationery", label: "Stationery" },
      { id: "cosmeticsStore", label: "Cosmetics Store" },
      {
        id: "hairdresserBeautyCenter",
        label: "Hairdresser & Beauty Center",
      },
      { id: "courseTrainingCenter", label: "Course & Training Center" },
      { id: "dryCleaning", label: "Dry Cleaning" },
      { id: "nutsSeller", label: "Nuts Seller" },
      { id: "jeweler", label: "Jeweler" },
      { id: "themePark", label: "Theme park" },
      { id: "mineQuarry", label: "Mine Quarry" },
      { id: "greengrocer", label: "Greengrocer" },
      { id: "market", label: "Market" },
      { id: "printingPress", label: "Printing press" },
      { id: "medicalMarket", label: "Medical Market" },
      { id: "fashionHouse", label: "Fashion House" },
      { id: "surgery", label: "Surgery" },
      { id: "shippingCargo", label: "Shipping & Cargo" },
      { id: "hardware", label: "Hardware" },
      { id: "schoolCourse", label: "School & Course" },
      { id: "parkingGarage", label: "Parking & Garage" },
      { id: "autoServiceMaintenance", label: "Auto Service & Maintenance" },
      { id: "autoSpareParts", label: "Auto Spare Parts" },
      { id: "carWashHairdresser", label: "Car Wash & Hairdresser" },
      { id: "studentDormitory", label: "Student Dormitory" },
      {
        id: "patisserieBakeryDessert",
        label: "Patisserie, Bakery & Dessert",
      },
      { id: "marketplace", label: "Market place" },
      { id: "petShop", label: "Pet Shop" },
      { id: "plaza", label: "Plaza" },
      { id: "plazaFloorOffice", label: "Plaza Floor & Office" },
      {
        id: "rehearsalRecordingStudio",
        label: "Rehearsal & Recording Studio",
      },
      { id: "radioStationTvChannel", label: "Radio Station & TV Channel" },
      { id: "restaurantDiner", label: "Restaurant & Diner" },
      { id: "residenceFloorOffice", label: "Residence Floor & Office" },
      { id: "watchShop", label: "Watch Shop" },
      { id: "healthCenter", label: "Health Center" },
      { id: "vegetableFruitMarket", label: "Vegetable & Fruit Market" },
      { id: "cinemaConferenceHall", label: "Cinema & Conference Hall" },
      { id: "coldStorage", label: "Cold Storage" },
      { id: "spaTurkishBathSauna", label: "SPA, Turkish Bath & Sauna" },
      { id: "sportsFacility", label: "Sports Facility" },
      { id: "waterTubeDealer", label: "Water & Tube Dealer" },
      { id: "gamesOfChanceDealer", label: "Games of Chance Dealer" },
      { id: "delicatessen", label: "Delicatessen" },
      { id: "taxiStand", label: "Taxi Stand" },
      { id: "garage", label: "Garage" },
      { id: "monopolyDealer", label: "Monopoly Dealer" },
      { id: "technicalService", label: "Technical Service" },
      { id: "tailor", label: "Tailor" },
      { id: "haberdashery", label: "Haberdashery" },
      { id: "toilet", label: "Toilet" },
      { id: "vet", label: "Vet" },
      { id: "glassware", label: "Glassware" },
    ],
    subletForRent: [
      { id: "privateOffice", label: "Private Office" },
      { id: "agency", label: "Agency" },
      { id: "fuelStation", label: "Fuel Station" },
      { id: "herbSpiceShop", label: "Herb & Spice Shop" },
      { id: "kindergartenNursery", label: "Kindergarten & Nursery" },
      { id: "apartmentHouse", label: "Apartment House" },
      { id: "vehicleShowroomService", label: "Vehicle Showroom & Service" },
      { id: "workshop", label: "Workshop" },
      { id: "shoppingMallStand", label: "Shopping Mall Stand" },
      { id: "fisherman", label: "Fisherman" },
      { id: "bar", label: "Bar" },
      { id: "bijouterie", label: "Bijouterie" },
      { id: "tuckshop", label: "Tuckshop" },
      { id: "buffet", label: "Buffet" },
      { id: "bureauOffice", label: "Bureau & Office" },
      { id: "cafe", label: "Cafe" },
      { id: "cdDvdStore", label: "CD & DVD Store" },
      { id: "mobilePhoneShop", label: "Mobile Phone Shop" },
      { id: "laundry", label: "Laundry" },
      { id: "teaHouse", label: "Tea House" },
      { id: "floristNursery", label: "Florist & Nursery" },
      { id: "farm", label: "Farm" },
      { id: "warehouseDepot", label: "Warehouse & Depot" },
      { id: "weddingHall", label: "Wedding Hall" },
      { id: "shopStore", label: "Shop & Store" },
      { id: "pharmacyMedical", label: "Pharmacy & Medical" },
      {
        id: "electricianHardwareStore",
        label: "Electrician & Hardware Store",
      },
      { id: "electronicsStore", label: "Electronics Store" },
      {
        id: "factoryProductionFacility",
        label: "Factory & Production Facility",
      },
      { id: "billingCenter", label: "Billing Center" },
      { id: "photoStudio", label: "Photo Studio" },
      { id: "nightClubDisco", label: "Night Club & Disco" },
      { id: "clothingStore", label: "Clothing Store" },
      { id: "optician", label: "Optician" },
      { id: "carpetWashing", label: "Carpet Washing" },
      { id: "nursingHome", label: "Nursing Home" },
      { id: "workshop2", label: "Workshop" },
      { id: "internetGameCafe", label: "Internet & Game Cafe" },
      { id: "businessCenter", label: "Business Center" },
      {
        id: "businessCenterFloorOffice",
        label: "Business Center Floor & Office",
      },
      { id: "butcher", label: "Butcher" },
      { id: "countryBreakfastGarden", label: "Country & Breakfast Garden" },
      { id: "coffeehouse", label: "Coffeehouse" },
      { id: "stationery", label: "Stationery" },
      { id: "cosmeticsStore", label: "Cosmetics Store" },
      {
        id: "hairdresserBeautyCenter",
        label: "Hairdresser & Beauty Center",
      },
      { id: "courseTrainingCenter", label: "Course & Training Center" },
      { id: "dryCleaning", label: "Dry Cleaning" },
      { id: "nutsSeller", label: "Nuts Seller" },
      { id: "jeweler", label: "Jeweler" },
      { id: "themePark", label: "Theme park" },
      { id: "mineQuarry", label: "Mine Quarry" },
      { id: "greengrocer", label: "Greengrocer" },
      { id: "market", label: "Market" },
      { id: "printingPress", label: "Printing press" },
      { id: "medicalMarket", label: "Medical Market" },
      { id: "fashionHouse", label: "Fashion House" },
      { id: "surgery", label: "Surgery" },
      { id: "shippingCargo", label: "Shipping & Cargo" },
      { id: "hardware", label: "Hardware" },
      { id: "schoolCourse", label: "School & Course" },
      { id: "parkingGarage", label: "Parking & Garage" },
      { id: "autoServiceMaintenance", label: "Auto Service & Maintenance" },
      { id: "autoSpareParts", label: "Auto Spare Parts" },
      { id: "carWashHairdresser", label: "Car Wash & Hairdresser" },
      { id: "studentDormitory", label: "Student Dormitory" },
      {
        id: "patisserieBakeryDessert",
        label: "Patisserie, Bakery & Dessert",
      },
      { id: "marketplace", label: "Market place" },
      { id: "petShop", label: "Pet Shop" },
      { id: "plaza", label: "Plaza" },
      { id: "plazaFloorOffice", label: "Plaza Floor & Office" },
      {
        id: "rehearsalRecordingStudio",
        label: "Rehearsal & Recording Studio",
      },
      { id: "radioStationTvChannel", label: "Radio Station & TV Channel" },
      { id: "restaurantDiner", label: "Restaurant & Diner" },
      { id: "residenceFloorOffice", label: "Residence Floor & Office" },
      { id: "watchShop", label: "Watch Shop" },
      { id: "healthCenter", label: "Health Center" },
      { id: "vegetableFruitMarket", label: "Vegetable & Fruit Market" },
      { id: "cinemaConferenceHall", label: "Cinema & Conference Hall" },
      { id: "coldStorage", label: "Cold Storage" },
      { id: "spaTurkishBathSauna", label: "SPA, Turkish Bath & Sauna" },
      { id: "sportsFacility", label: "Sports Facility" },
      { id: "waterTubeDealer", label: "Water & Tube Dealer" },
      { id: "gamesOfChanceDealer", label: "Games of Chance Dealer" },
      { id: "delicatessen", label: "Delicatessen" },
      { id: "taxiStand", label: "Taxi Stand" },
      { id: "garage", label: "Garage" },
      { id: "monopolyDealer", label: "Monopoly Dealer" },
      { id: "technicalService", label: "Technical Service" },
      { id: "tailor", label: "Tailor" },
      { id: "haberdashery", label: "Haberdashery" },
      { id: "toilet", label: "Toilet" },
      { id: "vet", label: "Vet" },
      { id: "glassware", label: "Glassware" },
    ],
    housingForSale: [
      { id: "apartment", label: "Apartment" },
      { id: "villa", label: "Villa" },
    ],
   hotel: [
  { id: "hotelForSale", label: "Hotel For Sale" },
  { id: "hotelForRent", label: "Hotel For Rent" },
  { id: "hotel", label: "Hotel" },
  { id: "apartHotel", label: "Apart Hotel" },
  { id: "boutiqueHotel", label: "Boutique Hotel" },
  { id: "motel", label: "Motel" },
  { id: "hostel", label: "Hostel" },
  { id: "campingSiteMocamp", label: "Camping Site (Mocamp)" },
  { id: "holidayVillage", label: "Holiday Village" },
],
resort: [
  { id: "hotelForSale", label: "Hotel For Sale" },
  { id: "hotelForRent", label: "Hotel For Rent" },
  { id: "hotel", label: "Hotel" },
  { id: "apartHotel", label: "Apart Hotel" },
  { id: "boutiqueHotel", label: "Boutique Hotel" },
  { id: "motel", label: "Motel" },
  { id: "hostel", label: "Hostel" },
  { id: "campingSiteMocamp", label: "Camping Site (Mocamp)" },
  { id: "holidayVillage", label: "Holiday Village" },
  { id: "beach", label: "Beach" },
]
  },
};
