// 📁 src/config/categories/vehicle.js
export const vehicleConfig = {
  title: "Vehicle",
  level1: [
    { id: "car", label: "Car" },
    { id: "offRoadSuvPickup", label: "Off-Road, SUV & Pickup" },
    { id: "electricVehicles", label: "Electric Vehicles" },
    { id: "motorcycle", label: "Motorcycle" },
    { id: "minivanPanelVan", label: "Minivan & Panel Van" },
    { id: "commercialVehicles", label: "Commercial Vehicles" },
    { id: "marineVehicles", label: "Marine Vehicles" },
    { id: "damagedVehicles", label: "Damaged Vehicles" },
    { id: "caravan", label: "Caravan" },
    { id: "classicVehicles", label: "Classic Vehicles" },
    { id: "aircraft", label: "Aircraft" },
    { id: "atv", label: "ATV" },
    { id: "utv", label: "UTV" },
  ],
  level2: {
    car: [
      { id: "year2024", label: "2024" },
      { id: "year2023", label: "2023" },
      { id: "year2022", label: "2022" },
      { id: "year2021", label: "2021" },
      { id: "year2020", label: "2020" },
      { id: "year2019", label: "2019" },
      { id: "year2018", label: "2018" },
      { id: "year2017", label: "2017" },
      { id: "year2016", label: "2016" },
      { id: "year2015", label: "2015" },
      { id: "year2014", label: "2014" },
      { id: "year2013", label: "2013" },
      { id: "year2012", label: "2012" },
      { id: "year2011", label: "2011" },
      { id: "year2010", label: "2010" },
      { id: "year2009", label: "2009" },
      { id: "year2008", label: "2008" },
      { id: "year2007", label: "2007" },
      { id: "year2006", label: "2006" },
      { id: "year2005", label: "2005" },
      { id: "year2004", label: "2004" },
      { id: "year2003", label: "2003" },
      { id: "year2002", label: "2002" },
      { id: "year2001", label: "2001" },
      { id: "year2000", label: "2000" },
      { id: "year1999", label: "1999" },
      { id: "year1998", label: "1998" },
      { id: "year1997", label: "1997" },
      { id: "year1996", label: "1996" },
      { id: "year1995", label: "1995" },
      { id: "year1994", label: "1994" },
      { id: "year1993", label: "1993" },
      { id: "year1992", label: "1992" },
      { id: "year1991", label: "1991" },
      { id: "year1990", label: "1990" },
      { id: "year1989", label: "1989" },
      { id: "year1988", label: "1988" },
      { id: "year1987", label: "1987" },
      { id: "year1986", label: "1986" },
      { id: "year1985", label: "1985" },
      { id: "year1984", label: "1984" },
      { id: "year1983", label: "1983" },
      { id: "year1982", label: "1982" },
      { id: "year1981", label: "1981" },
      { id: "year1980", label: "1980" },
      { id: "year1979", label: "1979" },
      { id: "year1978", label: "1978" },
      { id: "year1977", label: "1977" },
      { id: "year1976", label: "1976" },
      { id: "year1975", label: "1975" },
      { id: "year1974", label: "1974" },
      { id: "year1973", label: "1973" },
      { id: "year1972", label: "1972" },
      { id: "year1971", label: "1971" },
      { id: "year1970", label: "1970" },
    ],
    offRoadSuvPickup: [
      { id: "year2024", label: "2024" },
      { id: "year2023", label: "2023" },
      { id: "year2022", label: "2022" },
      { id: "year2021", label: "2021" },
      { id: "year2020", label: "2020" },
      { id: "year2019", label: "2019" },
      { id: "year2018", label: "2018" },
      { id: "year2017", label: "2017" },
      { id: "year2016", label: "2016" },
      { id: "year2015", label: "2015" },
      { id: "year2014", label: "2014" },
      { id: "year2013", label: "2013" },
      { id: "year2012", label: "2012" },
      { id: "year2011", label: "2011" },
      { id: "year2010", label: "2010" },
      { id: "year2009", label: "2009" },
      { id: "year2008", label: "2008" },
      { id: "year2007", label: "2007" },
      { id: "year2006", label: "2006" },
      { id: "year2005", label: "2005" },
      { id: "year2004", label: "2004" },
      { id: "year2003", label: "2003" },
      { id: "year2002", label: "2002" },
      { id: "year2001", label: "2001" },
      { id: "year2000", label: "2000" },
      { id: "year1999", label: "1999" },
      { id: "year1998", label: "1998" },
      { id: "year1997", label: "1997" },
      { id: "year1996", label: "1996" },
      { id: "year1995", label: "1995" },
      { id: "year1994", label: "1994" },
      { id: "year1993", label: "1993" },
      { id: "year1992", label: "1992" },
      { id: "year1991", label: "1991" },
      { id: "year1990", label: "1990" },
      { id: "year1989", label: "1989" },
      { id: "year1988", label: "1988" },
      { id: "year1987", label: "1987" },
      { id: "year1986", label: "1986" },
      { id: "year1985", label: "1985" },
      { id: "year1984", label: "1984" },
      { id: "year1983", label: "1983" },
      { id: "year1982", label: "1982" },
    ],
    electricVehicles:[
      { id: "electric-motorcycle", label: "Electric Motorcycle"},
      { id: "electric-atv", label: "Electric ATV"},
      { id: "electric-utv", label: "Electric UTV"},
      { id: "Electric-kickscooter", label: "Electric Kickscooter"},
      { id: "electric-utility-vehicles", label: "Electric Utility Vehicles"}
    ],
    motorcycle: [
      { id: "forSale", label: "For Sale" },
      { id: "forRent", label: "For Rent" },
    ],
    minivanPanelVan:[
      { id: "year2024", label: "2024" },
      { id: "year2023", label: "2023" },
      { id: "year2022", label: "2022" },
      { id: "year2021", label: "2021" },
      { id: "year2020", label: "2020" },
      { id: "year2019", label: "2019" },
      { id: "year2018", label: "2018" },
      { id: "year2017", label: "2017" },
      { id: "year2016", label: "2016" },
      { id: "year2015", label: "2015" },
      { id: "year2014", label: "2014" },
      { id: "year2013", label: "2013" },
      { id: "year2012", label: "2012" },
      { id: "year2011", label: "2011" },
      { id: "year2010", label: "2010" },
      { id: "year2009", label: "2009" },
      { id: "year2008", label: "2008" },
      { id: "year2007", label: "2007" },
      { id: "year2006", label: "2006" },
      { id: "year2005", label: "2005" },
      { id: "year2004", label: "2004" },
      { id: "year2003", label: "2003" },
      { id: "year2002", label: "2002" },
      { id: "year2001", label: "2001" },
      { id: "year2000", label: "2000" },
      { id: "year1999", label: "1999" },
      { id: "year1998", label: "1998" },
      { id: "year1997", label: "1997" },
      { id: "year1996", label: "1996" },
      { id: "year1995", label: "1995" },
      { id: "year1994", label: "1994" },
      { id: "year1993", label: "1993" },
      { id: "year1992", label: "1992" },
      { id: "year1991", label: "1991" },
      { id: "year1990", label: "1990" },
      { id: "year1989", label: "1989" },
      { id: "year1988", label: "1988" },
      { id: "year1987", label: "1987" },
      { id: "year1986", label: "1986" },
      { id: "year1985", label: "1985" },
    ],
    marineVehicles:[
      { id: "forSale", label: "For Sale" },
      { id: "forRent", label: "For Rent" },
    ],
    damagedVehicles:[
      { id: "car", label: "Car"},
      { id: "off-road", label: "Off-Road, SUV & Pickup"},
      { id: "motorcycle", label: "Motorcycle"},
      { id: "minivan", label: "Minivan & Panel Van"},
      { id: "commercialVehicles", label: "Commercial Vehicles"}
    ],
    caravan:[
      { id: "trailerCaravan", label: "Trailer Caravan"},
      { id: "motorhome", label: "Motorhome"}
    ],
    classicVehicles:[
      { id: "classicCars", label: "Classic Cars"},
      { id: "classicOffRoad", label: "Classic Off-Road Vehicles"},
      { id: "classicMotorcycles", label: "Classic Motorcycles"},
      { id: "classicCommercialVehicles", label: "Classic Commercial Vehicles"}
    ],
    aircraft:[
      { id: "seaplane", label: "Seaplane"},
      { id: "helicopter", label: "Helicopter"},
      { id: "privateJet", label: "Private Jet"},
      { id: "paramotors", label: "Paramotors"},
      { id: "glider", label: "Glider"},
      { id: "aeroplane", label: "Aeroplane"},
      { id: "hangGliding", label: "Hang Gliding & Microlight"},
      { id: "zeppelin", label: "Zeppelin"}
    ],
    atv:[
      { id: "access", label: "Access"},
      { id: "aeon", label: "Aeon"},
      { id: "altai", label: "Altai"},
      { id: "aodes", label: "Aodes"},
      { id: "apache1", label: "Apache"},
      { id: "apache2", label: "Apache"},
      { id: "arcticCat", label: "Arctic Cat"},
      { id: "slang", label: "Slang"},
      { id: "aro", label: "Aro"},
      { id: "asiaMotor", label: "Asia Motors"},
      { id: "barossa", label: "Barossa"},
      { id: "bashan", label: "Bashan"}
    ]
  },
  level3: {
  year2024: [
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'byd', label: 'BYD' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'cupra', label: 'Cupra' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'dsAutomobiles', label: 'DS Automobiles' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tesla', label: 'Tesla' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
   year2023: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'cupra', label: 'Cupra' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'dsAutomobiles', label: 'DS Automobiles' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'leapmotor', label: 'Leapmotor' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mg', label: 'MG' },
  { id: 'mini', label: 'Mini' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tesla', label: 'Tesla' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
  { id: 'voyage', label: 'Voyage' },
  { id: 'yudo', label: 'Yudo' },
],
 year2022: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'cupra', label: 'Cupra' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'dsAutomobiles', label: 'DS Automobiles' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsRoyce', label: 'Rolls Royce' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
 year2021: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bentley', label: 'Bentley' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'cupra', label: 'Cupra' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'dsAutomobiles', label: 'DS Automobiles' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'koenigsegg', label: 'Koenigsegg' },
  { id: 'lada', label: 'Lada' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'morgan', label: 'Morgan' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsRoyce', label: 'Rolls Royce' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tesla', label: 'Tesla' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
]
,
   year2020: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bentley', label: 'Bentley' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'koenigsegg', label: 'Koenigsegg' },
  { id: 'lada', label: 'Lada' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'morgan', label: 'Morgan' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsRoyce', label: 'Rolls Royce' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tesla', label: 'Tesla' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
   year2019: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bentley', label: 'Bentley' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'koenigsegg', label: 'Koenigsegg' },
  { id: 'lada', label: 'Lada' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'morgan', label: 'Morgan' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsRoyce', label: 'Rolls Royce' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tesla', label: 'Tesla' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
    year2018: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bentley', label: 'Bentley' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'dsAutomobiles', label: 'DS Automobiles' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'koenigsegg', label: 'Koenigsegg' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'morgan', label: 'Morgan' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsRoyce', label: 'Rolls Royce' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tesla', label: 'Tesla' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
],
    year2017: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bentley', label: 'Bentley' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'dsAutomobiles', label: 'DS Automobiles' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'koenigsegg', label: 'Koenigsegg' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'morgan', label: 'Morgan' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsRoyce', label: 'Rolls Royce' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tesla', label: 'Tesla' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
   year2016: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bentley', label: 'Bentley' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'dsAutomobiles', label: 'DS Automobiles' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'koenigsegg', label: 'Koenigsegg' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'morgan', label: 'Morgan' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsRoyce', label: 'Rolls Royce' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tesla', label: 'Tesla' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
   year2015: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bentley', label: 'Bentley' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'dsAutomobiles', label: 'DS Automobiles' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'maybach', label: 'Maybach' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'morgan', label: 'Morgan' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsRoyce', label: 'Rolls Royce' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tata', label: 'Tata' },
  { id: 'tesla', label: 'Tesla' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
   year2014: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bentley', label: 'Bentley' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chery', label: 'Chery' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'dsAutomobiles', label: 'DS Automobiles' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'geely', label: 'Geely' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'maybach', label: 'Maybach' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'morgan', label: 'Morgan' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsRoyce', label: 'Rolls Royce' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tata', label: 'Tata' },
  { id: 'tesla', label: 'Tesla' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
    year2013: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bentley', label: 'Bentley' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chery', label: 'Chery' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'dsAutomobiles', label: 'DS Automobiles' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'geely', label: 'Geely' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'ikco', label: 'Ikco' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lada', label: 'Lada' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'maybach', label: 'Maybach' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'morgan', label: 'Morgan' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsRoyce', label: 'Rolls Royce' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tata', label: 'Tata' },
  { id: 'tesla', label: 'Tesla' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
],
year2012: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bentley', label: 'Bentley' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chery', label: 'Chery' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'dsAutomobiles', label: 'DS Automobiles' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'geely', label: 'Geely' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'ikco', label: 'Ikco' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lada', label: 'Lada' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'maybach', label: 'Maybach' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'morgan', label: 'Morgan' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsRoyce', label: 'Rolls Royce' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tata', label: 'Tata' },
  { id: 'tesla', label: 'Tesla' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
year2011: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bentley', label: 'Bentley' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chery', label: 'Chery' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'daihatsu', label: 'Daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'dsAutomobiles', label: 'DS Automobiles' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'geely', label: 'Geely' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'ikco', label: 'Ikco' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'koenigsegg', label: 'Koenigsegg' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'maybach', label: 'Maybach' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'morgan', label: 'Morgan' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsRoyce', label: 'Rolls Royce' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tata', label: 'Tata' },
  { id: 'tesla', label: 'Tesla' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
],
year2010: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bentley', label: 'Bentley' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chery', label: 'Chery' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'daihatsu', label: 'Daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'dsAutomobiles', label: 'DS Automobiles' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'geely', label: 'Geely' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'ikco', label: 'Ikco' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'koenigsegg', label: 'Koenigsegg' },
  { id: 'lada', label: 'Lada' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'maybach', label: 'Maybach' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'morgan', label: 'Morgan' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsRoyce', label: 'Rolls Royce' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tata', label: 'Tata' },
  { id: 'tesla', label: 'Tesla' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
year2009: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bentley', label: 'Bentley' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chery', label: 'Chery' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'daihatsu', label: 'Daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'geely', label: 'Geely' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'ikco', label: 'Ikco' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'koenigsegg', label: 'Koenigsegg' },
  { id: 'lada', label: 'Lada' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'maybach', label: 'Maybach' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'morgan', label: 'Morgan' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsRoyce', label: 'Rolls Royce' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tata', label: 'Tata' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
year2008: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bentley', label: 'Bentley' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chery', label: 'Chery' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'daihatsu', label: 'Daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'geely', label: 'Geely' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'ikco', label: 'Ikco' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'koenigsegg', label: 'Koenigsegg' },
  { id: 'lada', label: 'Lada' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'maybach', label: 'Maybach' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tata', label: 'Tata' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
year2007: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bentley', label: 'Bentley' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'daihatsu', label: 'Daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'koenigsegg', label: 'Koenigsegg' },
  { id: 'lada', label: 'Lada' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'maybach', label: 'Maybach' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tata', label: 'Tata' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
],
year2006: [
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'Daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'koenigsegg', label: 'Koenigsegg' },
  { id: 'lada', label: 'Lada' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'maybach', label: 'Maybach' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tata', label: 'Tata' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
year2005: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'Daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lada', label: 'Lada' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'maybach', label: 'Maybach' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mg', label: 'MG' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tata', label: 'Tata' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
year2004: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'Daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lada', label: 'Lada' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'maybach', label: 'Maybach' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mg', label: 'MG' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
year2003: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'Daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lada', label: 'Lada' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'maybach', label: 'Maybach' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mg', label: 'MG' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofaş' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
year2002: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'Daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lada', label: 'Lada' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'maybach', label: 'Maybach' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mg', label: 'MG' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofaş' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
year2001: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfaRomeo', label: 'Alfa Romeo' },
  { id: 'astonMartin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'Daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lada', label: 'Lada' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedesBenz', label: 'Mercedes Benz' },
  { id: 'mg', label: 'MG' },
  { id: 'mini', label: 'Mini' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsRoyce', label: 'Rolls Royce' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofaş' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' },
],
year2000: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'aston-martin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lada', label: 'Lada' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mg', label: 'MG' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'plymouth', label: 'Plymouth' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rolls-royce', label: 'Rolls Royce' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' }
],
year1999: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'aston-martin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'buick', label: 'Buick' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'eagle', label: 'Eagle' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lada', label: 'Lada' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'plymouth', label: 'Plymouth' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' }
],
year1998: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'aston-martin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'bugatti', label: 'Bugatti' },
  { id: 'buick', label: 'Buick' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'eagle', label: 'Eagle' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lada', label: 'Lada' },
  { id: 'lamborghini', label: 'Lamborghini' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'plymouth', label: 'Plymouth' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'smart', label: 'Smart' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' }
],
year1997: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'aston-martin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'buick', label: 'Buick' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'eagle', label: 'Eagle' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lada', label: 'Lada' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'plymouth', label: 'Plymouth' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rolls-royce', label: 'Rolls Royce' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' }
],
year1996: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'aston-martin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'buick', label: 'Buick' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'eagle', label: 'Eagle' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lada', label: 'Lada' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'plymouth', label: 'Plymouth' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rolls-royce', label: 'Rolls Royce' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' }
],
year1995: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'buick', label: 'Buick' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'eagle', label: 'Eagle' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lada', label: 'Lada' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'moscow-witness', label: 'Moscow Witness' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'oldsmobile', label: 'Oldsmobile' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'plymouth', label: 'Plymouth' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rolls-royce', label: 'Rolls Royce' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' }
]
,year1994: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'buick', label: 'Buick' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'eagle', label: 'Eagle' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lada', label: 'Lada' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'moscow-witness', label: 'Moscow Witness' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'oldsmobile', label: 'Oldsmobile' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'plymouth', label: 'Plymouth' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rolls-royce', label: 'Rolls Royce' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' }
],
year1993: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'aston-martin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'buick', label: 'Buick' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'eagle', label: 'Eagle' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia' },
  { id: 'lada', label: 'Lada' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'moscow-witness', label: 'Moscow Witness' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' }
],
year1992: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'aston-martin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'buick', label: 'Buick' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'eagle', label: 'Eagle' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'lada', label: 'Lada' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'moscow-witness', label: 'Moscow Witness' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' }
],
year1991: [
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'aston-martin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'buick', label: 'Buick' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'eagle', label: 'Eagle' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'isuzu', label: 'Isuzu' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'lada', label: 'Lada' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'moscow-witness', label: 'Moscow Witness' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' }
],
year1990: [
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'aston-martin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'buick', label: 'Buick' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'isuzu', label: 'Isuzu' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'lada', label: 'Lada' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'moscow-witness', label: 'Moscow Witness' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' }
], 
year1989:[
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'aston-martin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'buick', label: 'Buick' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'isuzu', label: 'Isuzu' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'lada', label: 'Lada' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'moscow-witness', label: 'Moscow Witness' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' }
],
year1988:[
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'aston-martin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'isuzu', label: 'Isuzu' },
  { id: 'lada', label: 'Lada' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'moscow-witness', label: 'Moscow Witness' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' }
],
year1987:[
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'buick', label: 'Buick' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'lada', label: 'Lada' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'moscow-witness', label: 'Moscow Witness' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
],
year1986: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'aston-martin', label: 'Aston Martin' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'buick', label: 'Buick' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'eagle', label: 'Eagle' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'infiniti', label: 'Infiniti' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'lada', label: 'Lada' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'moscow-witness', label: 'Moscow Witness' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsroyce', label: 'Rolls Royce'},
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' }
],
year1985: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'buick', label: 'Buick' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia'},
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'eagle', label: 'Eagle' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia'},
  { id: 'lada', label: 'Lada' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'moscow-witness', label: 'Moscow Witness' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'plymouth', label: 'Plymouth'},
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'proton', label: 'Proton' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsroyce', label: 'Rolls Royce'},
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' }
],

year1984: [
  { id: 'acura', label: 'Acura' },
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'buick', label: 'Buick' },
  { id: 'cadillac', label: 'Cadillac' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'chrysler', label: 'Chrysler' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'dacia', label: 'Dacia'},
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'eagle', label: 'Eagle' },
  { id: 'ferrari', label: 'Ferrari' },
  { id: 'fiat', label: 'Fiat' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'hyundai', label: 'Hyundai' },
  { id: 'jaguar', label: 'Jaguar' },
  { id: 'kia', label: 'Kia'},
  { id: 'lada', label: 'Lada' },
  { id: 'lancia', label: 'Lancia' },
  { id: 'lexus', label: 'Lexus' },
  { id: 'lincoln', label: 'Lincoln' },
  { id: 'lotus', label: 'Lotus' },
  { id: 'maserati', label: 'Maserati' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'mitsubishi', label: 'Mitsubishi' },
  { id: 'moscow-witness', label: 'Moscow Witness' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'pontiac', label: 'Pontiac' },
  { id: 'porsche', label: 'Porsche' },
  { id: 'renault', label: 'Renault' },
  { id: 'rollsroyce', label: 'Rolls Royce'},
  { id: 'rover', label: 'Rover' },
  { id: 'saab', label: 'Saab' },
  { id: 'seat', label: 'Seat' },
  { id: 'skoda', label: 'Skoda' },
  { id: 'subaru', label: 'Subaru' },
  { id: 'suzuki', label: 'Suzuki' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
  { id: 'volvo', label: 'Volvo' }
],
year1983: [
  { id: 'alfa-romeo', label: 'Alfa Romeo' },
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'citroen', label: 'Citroen' },
  { id: 'daewoo', label: 'Daewoo' },
  { id: 'daihatsu', label: 'daihatsu' },
  { id: 'dodge', label: 'Dodge' },
  { id: 'ford', label: 'Ford' },
  { id: 'honda', label: 'Honda' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'moscow-witness', label: 'Moscow Witness' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'renault', label: 'Renault' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
],
year1982: [
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'ford', label: 'Ford' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'moscow-witness', label: 'Moscow Witness' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'renault', label: 'Renault' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'toyota', label: 'Toyota' },
  { id: 'volkswagen', label: 'Volkswagen' },
],
year1981: [
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'ford', label: 'Ford' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'moscow-witness', label: 'Moscow Witness' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'renault', label: 'Renault' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'volkswagen', label: 'Volkswagen' },
],
year1980: [
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'ford', label: 'Ford' },
  { id: 'mazda', label: 'Mazda' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'moscow-witness', label: 'Moscow Witness' },
  { id: 'nissan', label: 'Nissan' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'renault', label: 'Renault' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'volkswagen', label: 'Volkswagen' },
],
year1979: [
  { id: 'audi', label: 'Audi' },
  { id: 'bmw', label: 'BMW' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'ford', label: 'Ford' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'renault', label: 'Renault' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'volkswagen', label: 'Volkswagen' },
],
year1978: [
  { id: 'bmw', label: 'BMW' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'ford', label: 'Ford' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'renault', label: 'Renault' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'volkswagen', label: 'Volkswagen' },
],
year1977: [
  { id: 'bmw', label: 'BMW' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'ford', label: 'Ford' },
  { id: 'opel', label: 'Opel' },
  { id: 'renault', label: 'Renault' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'volkswagen', label: 'Volkswagen' },
],
year1976: [
  { id: 'bmw', label: 'BMW' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'ford', label: 'Ford' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'opel', label: 'Opel' },
  { id: 'peugeot', label: 'Peugeot' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'volkswagen', label: 'Volkswagen' },
],
year1975: [
  { id: 'bmw', label: 'BMW' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'ford', label: 'Ford' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'opel', label: 'Opel' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'volkswagen', label: 'Volkswagen' },
],
year1974: [
  { id: 'bmw', label: 'BMW' },
  { id: 'chevy', label: 'Chevy' },
  { id: 'ford', label: 'Ford' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'opel', label: 'Opel' },
  { id: 'renault', label: 'Renault' },
  { id: 'tofas', label: 'Tofas' },
  { id: 'volkswagen', label: 'Volkswagen' },
],
year1973: [
  { id: 'chevy', label: 'Chevy' },
  { id: 'ford', label: 'Ford' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'opel', label: 'Opel' },
  { id: 'renault', label: 'Renault' },
  { id: 'tofas', label: 'Tofas' },
],
year1972: [
  { id: 'chevy', label: 'Chevy' },
  { id: 'ford', label: 'Ford' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'opel', label: 'Opel' },
  { id: 'renault', label: 'Renault' },
  { id: 'tofas', label: 'Tofas' },
],
year1971: [
  { id: 'ford', label: 'Ford' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
  { id: 'renault', label: 'Renault' },
  { id: 'tofas', label: 'Tofas' },
],
year1970: [
  { id: 'chevy', label: 'Chevy' },
  { id: 'ford', label: 'Ford' },
  { id: 'mercedes-benz', label: 'Mercedes Benz' },
],
    // Additional years can be added similarly
  },
};